// Lightweight DOM harness. Executes event handlers, not browser layout or pixels.
const voids=new Set(['input','br','hr','img','meta','link']);
const decode=s=>String(s).replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
class Element{
 constructor(tag,doc,attrs={}){this.tagName=tag;this.owner=doc;this.attrs=attrs;this.children=[];this.parent=null;this.style={};this.listeners={};this.disabled='disabled'in attrs;this.checked='checked'in attrs;this._value=attrs.value??'';this._valueSet=false;this._html='';this._text='';this.dataset={};for(const [k,v]of Object.entries(attrs))if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v;const set=new Set((attrs.class||'').split(' '));this.classList={add:(...s)=>s.forEach(x=>set.add(x)),remove:(...s)=>s.forEach(x=>set.delete(x)),contains:s=>set.has(s),toggle:s=>set.has(s)?set.delete(s):set.add(s)};this.clientWidth=900;}
 get id(){return this.attrs.id;} setAttribute(k,v){this.attrs[k]=String(v);}
 get textContent(){return this._text+this.children.map(c=>c.textContent).join('');}set textContent(s){this.children=[];this._text=String(s);this._html=String(s);}
 get innerHTML(){return this._html;}set innerHTML(s){this._html=String(s);this.children=[];this._text='';const stack=[this];for(const m of String(s).matchAll(/<\/?[a-zA-Z][^>]*>|[^<]+/g)){const part=m[0];if(part.startsWith('</')){if(stack.length>1)stack.pop();continue;}if(part.startsWith('<')){const tag=part.match(/^<([\w-]+)/)[1].toLowerCase(),attrs={};const rest=part.slice(tag.length+1,-1);for(const a of rest.matchAll(/([\w-]+)(?:="([^"]*)"|='([^']*)'|=([^\s>]+))?/g))attrs[a[1]]=decode(a[2]??a[3]??a[4]??'');const child=new Element(tag,this.owner,attrs);stack.at(-1).appendChild(child);if(!voids.has(tag))stack.push(child);}else stack.at(-1)._text+=decode(part);}}
 get value(){if(this.tagName==='select'){const options=this.querySelectorAll('option');if(this._valueSet)return this._value;const selected=options.find(x=>'selected'in x.attrs)||options[0];return selected?.attrs.value??selected?.textContent??'';}return this._value;}set value(v){this._value=String(v);this._valueSet=true;}
 appendChild(c){c.parent=this;this.children.push(c);return c;}remove(){if(this.parent)this.parent.children=this.parent.children.filter(x=>x!==this);}insertAdjacentHTML(_where,html){this.innerHTML=this.innerHTML+html;}
 matches(sel){if(sel.endsWith(':checked'))return this.checked&&this.matches(sel.slice(0,-8));if(sel.startsWith('#'))return this.id===sel.slice(1);if(sel.startsWith('.'))return (this.attrs.class||'').split(/\s+/).includes(sel.slice(1));if(sel.startsWith('['))return sel.slice(1,-1)in this.attrs;return this.tagName===sel;}
 querySelectorAll(sel){const parts=sel.split(/\s+/);const result=[];const walk=e=>{for(const c of e.children){if(c.matches(parts.at(-1))){if(parts.length===1||(()=>{let p=c.parent;while(p&&p!==this){if(p.matches(parts[0]))return true;p=p.parent;}return false;})())result.push(c);}walk(c);}};walk(this);return result;}
 querySelector(sel){return this.querySelectorAll(sel)[0]||null;}addEventListener(k,fn){this.listeners[k]=fn;}click(){if(this.disabled)return;const e={target:this,preventDefault(){}};return this.onclick?this.onclick(e):this.listeners.click?.(e);}scrollIntoView(){}getContext(){return new Proxy({},{get:()=>()=>{},set:()=>true});}toDataURL(){return 'data:image/png;base64,TEST';}
}
class Document{constructor(){this.body=new Element('body',this);this.head=new Element('head',this);}getElementById(id){return this.body.querySelector('#'+id);}createElement(tag){return new Element(tag,this);}querySelectorAll(sel){return this.body.querySelectorAll(sel);}}
module.exports={Document,Element};
