const assert=require('node:assert/strict'),C=require('../ai/research-core.js');
const dataset=rows=>({rows,cols:Object.keys(rows[0])});
const left=dataset([{Firm:'A',Date:'2021-01-31',RI:1},{Firm:'B',Date:'2021-01-31',RI:2},{Firm:'A',Date:'2021-02-28',RI:3},{Firm:'B',Date:'',RI:4}]);
const macro=dataset([{Date:'1/31/2021',Rate:0.1},{Date:'02/28/2021',Rate:0.2},{Date:'03/31/2021',Rate:0.3}]);
const cfg={keys:[{left:'Date',right:'Date',mode:'day'}],how:'left'};
let out=C.mergeDatasets(left,macro,cfg);assert.equal(out.rows.length,4);assert.deepEqual(out.rows.map(x=>x.Rate),[.1,.1,.2,null]);assert.equal(out.diagnostics.relationship,'Many-to-one');assert.equal(out.diagnostics.unusedRight,1);assert.equal(out.diagnostics.invalidLeft,1);assert(out.validated);assert.deepEqual(out.lineage.map(x=>x.leftRow),[1,2,3,4]);
assert.equal(C.mergeDatasets(left,macro,{...cfg,how:'inner'}).rows.length,3);
const panel=dataset([{Firm:'A',Date:'2021-01-31',RI:9,Size:10},{Firm:'B',Date:'2021-01-31',RI:8,Size:20},{Firm:'A',Date:'2021-02-28',RI:7,Size:30}]);
assert(C.inspectMerge(left,panel,cfg).blocked);assert.throws(()=>C.mergeDatasets(left,panel,cfg),/duplicate/);
const compound={keys:[{left:'Firm',right:'Firm',mode:'exact'},...cfg.keys],how:'left'};
out=C.mergeDatasets(left,panel,compound);assert.deepEqual(out.rows.map(r=>r.Size),[10,20,30,null]);assert.deepEqual(out.rows.map(r=>r.RI),[1,2,3,4]);assert.deepEqual(out.rows.map(r=>r.RI_right),[9,8,7,null]);assert.equal(out.diagnostics.relationship,'One-to-one');
assert.equal(C.suggestMerge(left,panel)[0].keys.length,2);assert.equal(C.suggestMerge(left,macro)[0].keys[0].mode,'day');
const monthly=dataset([{Month:'2021-01',Rate:3},{Month:'2021-02',Rate:4}]);
out=C.mergeDatasets(left,monthly,{how:'left',keys:[{left:'Date',right:'Month',mode:'month'}]});assert.deepEqual(out.rows.map(r=>r.Rate),[3,3,4,null]);
const tooMany=dataset([{Date:'2021-01-01',x:1},{Date:'2021-01-31',x:2}]);assert.throws(()=>C.mergeDatasets(left,tooMany,{how:'left',keys:[{left:'Date',right:'Date',mode:'month'}]}),/duplicate/);
assert.equal(C.calendarParts('2021-02-30'),null);assert.equal(C.calendarParts('13/1/2021'),null);assert.equal(C.calendarParts('2020-02-29').day,'29');
const bad=dataset([{Date:'2021-02-30',Rate:1},{Date:'',Rate:2}]);out=C.mergeDatasets(left,bad,cfg);assert.equal(out.diagnostics.matched,0);assert.equal(out.diagnostics.invalidRight,2);assert.equal(out.rows.length,left.rows.length);
const ids=dataset([{ID:'001'},{ID:'1'},{ID:' A '},{ID:'a'},{ID:null}]),lookup=dataset([{ID:1,X:2},{ID:'A',X:3},{ID:null,X:4}]);
out=C.mergeDatasets(ids,lookup,{how:'left',keys:[{left:'ID',right:'ID',mode:'exact'}]});assert.deepEqual(out.rows.map(r=>r.X),[null,2,3,null,null]);
const collision=dataset([{ID:'a',X:1,X_right:2}]);out=C.mergeDatasets(collision,dataset([{ID:'a',X:3}]),{how:'left',keys:[{left:'ID',right:'ID',mode:'exact'}]});assert.equal(out.rows[0].X_right3,3);
assert.throws(()=>C.inspectMerge(left,macro,{how:'full',keys:cfg.keys}),/left or inner/);assert.throws(()=>C.inspectMerge(left,macro,{how:'left',keys:[...cfg.keys,...cfg.keys]}),/distinct/);
assert.throws(()=>C.evaluateExpression('lag(RI,1)',[{Date:'2021-02-30',RI:1}],['Date','RI'],{time:'Date'}),/Time must/);
console.log('PASS: panel-to-macro / panel-to-panel joins, left/inner, duplicate-right blocking, month frequency collisions, invalid dates, blank keys, ID normalization, naming collisions, suggestions and exact row-count/lineage invariants.');
