const assert=require('node:assert/strict'),C=require('../ai/research-core.js'),W=require('../ai/research-workflow.js');
const data=Array.from({length:20},(_,i)=>({Date:'2024-01-'+String(i+1).padStart(2,'0'),x:i+1,y:1+2*i+Math.sin(i),z:i===3?'':Math.cos(i),screen:i===19?1000:i+1})),s={cols:Object.keys(data[0]),rows:data};
const spec={y:'y',xs:['x'],intercept:true,seType:'OLS',fixed:{}};
let r=W.sensitivity(data,spec,{kind:'outliers',metric:'screen'});assert.equal(r.baseline.n,20);assert.equal(r.variant.n,19);assert.equal(r.removed,1);assert.equal(r.added,0);assert(!r.variant.ids.includes(19));assert.equal(data.length,20);
r=W.sensitivity(data,spec,{kind:'period',time:'Date',start:'2024-01-03',end:'2024-01-12'});assert.equal(r.variant.n,10);assert.deepEqual(r.variant.ids,Array.from({length:10},(_,i)=>i+2));
r=W.sensitivity(data,spec,{kind:'predictors',xs:['x','z']});assert.equal(r.originalN,20);assert.equal(r.baseline.n,19);assert.deepEqual(r.baseline.ids,r.variant.ids);assert.equal(r.deltas.find(d=>d.name==='z').delta,null);assert.throws(()=>W.sensitivity(data,spec,{kind:'period',time:'Date',start:'2024-03-01',end:'2024-01-01'}),/Start date/);
const recipe={format:'dayrixa-workflow',version:1,columns:s.cols,steps:[{kind:'clean',options:{removeDuplicates:true}},{kind:'variables',variables:[{name:'Excess',formula:'y - x'}]},{kind:'merge',slot:'rates',rightColumns:['Date','Rf'],config:{how:'left',keys:[{left:'Date',right:'Date',mode:'day'}]}}],models:[{name:'Excess model',spec:{...spec,y:'Excess'}}]};
const right={cols:['Date','Rf'],rows:data.map((r,i)=>({Date:r.Date,Rf:i*.01}))};let run=W.replay(recipe,{...s,rows:[...data,data[0]]},{rates:right});assert.equal(run.state.rows.length,20);assert.equal(run.audit[0].before,21);assert.equal(run.audit[0].after,20);assert.equal(run.models.length,1);assert.equal(run.state.rows[2].Excess,data[2].y-data[2].x);assert.equal(run.state.rows[2].Rf,.02);
const newRows=data.map(r=>({...r,y:r.y+3}));let next=W.replay(recipe,{...s,rows:newRows},{rates:right});assert(Math.abs(next.models[0].terms[0].beta-run.models[0].terms[0].beta-3)<1e-10);
assert.throws(()=>W.replay(recipe,s,{}),/Upload the new right-hand/);assert.throws(()=>W.replay(recipe,s,{rates:{...right,rows:[...right.rows,right.rows[0]]}}),/Step 3:.*duplicate/);assert.throws(()=>W.replay(recipe,{...s,cols:s.cols.filter(c=>c!=='x')},{rates:right}),/Missing required/);assert.throws(()=>W.replay({...recipe,steps:[{kind:'unsupported',reason:'Manual row deletion'}]},s),/cannot be replayed/);
assert(!s.cols.includes('Excess'));assert(!('Excess'in s.rows[0]));
const hs={cols:['parent','parent_2'],rows:[{parent:'x',parent_2:'y'},{parent:1,parent_2:2}],rawGrid:[['parent','parent'],['x','y'],[1,2]],headerSuggestion:{dataStart:2,meta:[{display:'parent — x'},{display:'parent — y'}]}};
const h=W.applyStep(hs,{kind:'headers',columns:['parent — x','parent — y']});assert.equal(h.rows.length,1);assert.equal(h.rows[0]['parent — x'],1);assert.throws(()=>W.applyStep(hs,{kind:'headers',columns:['different']}),/Header structure/);
const tex=W.latex('A_% & \\input{bad}',[{...C.fit(data,spec),name:'Model #1'}],{notes:'literal $x$ {a}'});assert(tex.includes('A\\_\\% \\& \\textbackslash{}input\\{bad\\}'));assert(!tex.includes('\\input{bad}'));assert(tex.includes('\\begin{longtable}'));assert(tex.endsWith('\\end{document}\n'));
console.log('PASS: sensitivity sample membership/counts, shared-sample predictors, inclusive periods, nonmutation; replay clean/derive/merge/refit, changed-input recomputation, schema/duplicate/missing-file rejection; headers and LaTeX escaping.');
// Replaying stored common-sample comparison and scenario must recompute both.
const extended={...recipe,comparison:{common:true,models:[{name:'Base',spec},{name:'With z',spec:{...spec,xs:['x','z']}}]},sensitivity:{spec,options:{kind:'period',time:'Date',start:'2024-01-01',end:'2024-01-10'}}};
const replayed=W.replay(extended,s,{rates:right});assert.equal(replayed.comparison.models[0].n,19);assert.deepEqual(replayed.comparison.models[0].ids,replayed.comparison.models[1].ids);assert.equal(replayed.sensitivityResult.variant.n,10);
