/* DAYRIXA Research Studio — local, inspectable research workflow. */
(function(root){'use strict';
root.createDAYRIXAStudio=function(bridge){
 const C=root.DAYRIXAResearch,W=root.DAYRIXAWorkflow,mount=document.getElementById('researchStudio');if(!mount||!C)return null;
 const E=C.escape,F=v=>Number.isFinite(v)?(v!==0&&Math.abs(v)<0.0001?v.toExponential(4):v.toFixed(4)):'—';
 let reportTitle='',researchNotes='',project='Untitled study',source='',revision=0,serial=0,journal=[],snapshots=[],cursor=-1,models=[],derived=[],preview=null,lastFit=null,comparison=null,page='guide',secondary=null,mergePreview=null,recipe=[],sensitivityResult=null,replayRecipe=null,replayFiles={},replayInput=null,replayResult=null;
 const $=id=>document.getElementById(id),now=()=>new Date().toISOString();
 const opts=(values,selected='',none=false)=>(none?'<option value="">None / single series</option>':'')+values.map(v=>`<option value="${E(v)}" ${selected===v?'selected':''}>${E(v)}</option>`).join('');
 function state(){return bridge.get();}
 function recordState(){return {...state(),recipe:JSON.parse(JSON.stringify(recipe)),derived:derived.map(x=>({...x}))};}
 function setState(s){replayResult=null;recipe=JSON.parse(JSON.stringify(s.recipe||[]));sensitivityResult=null;derived=(s.derived||[]).map(x=>({...x}));bridge.set(s);preview=null;lastFit=null;comparison=null;}
 function entry(action,detail,before,after){journal.push({at:now(),action,detail,revision,rowsBefore:before?.rows.length??0,rowsAfter:after.rows.length,columnsBefore:before?.cols.length??0,columnsAfter:after.cols.length});}
 function different(a,b){if(JSON.stringify(a.recipe||[])!==JSON.stringify(b.recipe||[]))return true;if(a.rows.length!==b.rows.length||a.cols.join('\0')!==b.cols.join('\0')||JSON.stringify(a.rawGrid)!==JSON.stringify(b.rawGrid))return true;return a.rows.some((r,i)=>a.cols.some(c=>r[c]!==b.rows[i][c]));}
 function commit(action,detail,before){const after=recordState();if(!different(before,after))return false;revision=++serial;entry(action,detail,before,after);snapshots=snapshots.slice(0,cursor+1);snapshots.push({revision,state:recordState()});if(snapshots.length>13)snapshots.shift();cursor=snapshots.length-1;preview=null;lastFit=null;comparison=null;render();return true;}
 function mutate(action,detail,operation,step=null){const before=recordState();try{operation();const changed=different({...before,recipe:[]},{...state(),recipe:[]});if(action==='Restore original'){derived=[];recipe=[];}else{derived=derived.filter(v=>state().cols.includes(v.name));if(step)recipe.push(JSON.parse(JSON.stringify(step)));else if(changed)recipe.push({kind:'unsupported',reason:action+' — '+detail});}sensitivityResult=null;replayResult=null;return commit(action,detail,before);}catch(e){setState(before);throw e;}}

 function reset(name){recipe=[];sensitivityResult=null;replayRecipe=null;replayFiles={};replayInput=null;replayResult=null;secondary=null;mergePreview=null;reportTitle='';researchNotes='';project=name.replace(/\.[^.]+$/,'')||'Untitled study';source=name;revision=serial=1;journal=[];models=[];derived=[];lastFit=preview=comparison=null;entry('Import',name,null,state());snapshots=[{revision,state:recordState()}];cursor=0;page='guide';render();}
 function undo(direction){const target=cursor+direction;if(target<0||target>=snapshots.length)return;const before=state();cursor=target;revision=snapshots[cursor].revision;setState(snapshots[cursor].state);entry(direction<0?'Undo':'Redo','Restored data revision '+revision,before,state());render();}
 function run(fn){try{const result=fn();if(result?.catch)result.catch(error=>errorMessage(error));}catch(error){errorMessage(error);}}
 function errorMessage(e){const out=$('studioMessage');if(out){out.setAttribute('role','alert');out.textContent=e.message||String(e);out.className='studio-message error';}}
 function message(s){const out=$('studioMessage');if(out){out.textContent=s;out.className='studio-message';}}
 function button(id,text,cls='secondary'){return `<button type="button" id="${id}" class="${cls}">${text}</button>`;}
 function render(){
 const s=state();if(!s.rows.length&&!s.cols.length){mount.innerHTML='';return;}
 const tabs=[['guide','01','Start'],['prepare','02','Data'],['models','03','Analysis'],['export','04','Results']];
 mount.innerHTML=`<section class="studio"><div class="studio-heading"><div><span class="studio-eyebrow">DAYRIXA · RESEARCH STUDIO 3.5</span><h2>Your next research result.</h2><p>Prepare your data. Test a decision. Repeat your work.</p></div><span class="studio-badge">LOCAL WORKSPACE</span></div><div class="studio-callout"><strong>${source==='Synthetic_finance_demo.csv'?'SYNTHETIC DEMO — not your uploaded research data':'Active source: '+E(source)}</strong><p>${source==='Synthetic_finance_demo.csv'?'These 60 generated rows are for practice. Upload your actual CSV or Excel above to analyze your own observations. Rf is constant at 0.1 in this demo.':'Check the filename and working-data preview before fitting a model.'}</p></div><div class="studio-project"><label>Study name<input id="studioProject" maxlength="120" value="${E(project)}"></label><div class="studio-meta">${E(source)}<br>Data revision ${revision} · ${s.rows.length.toLocaleString()} rows · ${s.cols.length} variables · ${models.length} saved models</div><div class="studio-undo">${button('studioUndo','↶ Undo')}${button('studioRedo','↷ Redo')}</div></div><nav class="studio-tabs" aria-label="Research workflow">${tabs.map(([id,n,label])=>`<button type="button" data-studio-tab="${id}" aria-current="${(page===id||(id==='prepare'&&['variables','merge','history','workflow'].includes(page)))?'page':'false'}"><small>${n}</small>${label}</button>`).join('')}</nav><div id="studioMessage" role="status" aria-live="polite"></div>${s.headerSuggestion?`<div class="studio-callout"><strong>Multiple header rows detected — review before analysis</strong><p>The current import may include a header row as data. Proposed column names: ${s.headerSuggestion.meta.map(m=>E(m.display)).join('; ')}</p>${button('studioApplyHeader','Use detected headers','primary')}</div>`:''}<div id="studioBody"></div><p class="studio-foot">Your file stays in this browser. Save a project file before closing to keep data, history and model results.</p></section>`;
 if($('studioApplyHeader'))$('studioApplyHeader').onclick=()=>run(()=>mutate('Interpret headers','Applied '+s.headerSuggestion.dataStart+' source header rows',()=>{const hs=s.headerSuggestion,names=hs.meta.map(m=>m.display),data=s.rawGrid.slice(hs.dataStart).filter(row=>row.some(v=>!C.blank(v))).map(row=>Object.fromEntries(names.map((name,i)=>[name,row[i]??''])));bridge.set({...s,cols:names,rows:data,headerSuggestion:null});},{kind:'headers',columns:s.headerSuggestion.meta.map(m=>m.display)}));
 $('studioProject').onchange=e=>{project=e.target.value.trim()||'Untitled study';};$('studioUndo').disabled=cursor<=0;$('studioRedo').disabled=cursor>=snapshots.length-1;
 $('studioUndo').onclick=()=>run(()=>undo(-1));$('studioRedo').onclick=()=>run(()=>undo(1));
 mount.querySelectorAll('[data-studio-tab]').forEach(b=>b.onclick=()=>{page=b.dataset.studioTab;preview=null;render();});
 ({guide:renderGuide,prepare:renderPrepare,workflow:renderWorkflow,variables:renderVariables,models:renderModels,merge:renderMerge,history:renderHistory,export:renderExport})[page]();
 }
 function renderGuide(){
 const s=state(),missing=s.rows.reduce((sum,r)=>sum+s.cols.filter(c=>C.blank(r[c])).length,0);
 $('studioBody').innerHTML=`<div class="studio-section-title"><h3>What do you want to do?</h3><span>${missing} missing cells · ${s.rows.length} working rows</span></div><div class="studio-guide"><article><span class="studio-card-number">01 / DATA</span><h4>Understand and prepare</h4><p>Review your sample, handle missing values and create research variables.</p><button class="primary" data-start="prepare">Explore my data</button></article><article><span class="studio-card-number">02 / COMBINE</span><h4>Connect two datasets</h4><p>Choose matching keys and check the row counts before applying a join.</p><button class="secondary" data-start="merge">Combine files</button></article><article><span class="studio-card-number">03 / ANALYZE</span><h4>Explain a relationship</h4><p>Fit a model or CAPM, then inspect how a different decision changes the result.</p><button class="secondary" data-start="models">Build my analysis</button></article></div><div class="studio-next"><div><strong>Already did this last month?</strong><p>Run your recorded preparation and model definitions on new files.</p></div><button class="secondary" data-start="workflow">Repeat my work</button></div>`;
 mount.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>navigate(b.dataset.start));
 }
 function navigate(target){page=target;render();}
 function renderPrepare(){
 const s=state();$('studioBody').innerHTML=`<div class="studio-section-title"><h3>Prepare your data</h3><span>${s.rows.length} rows · ${s.cols.length} columns</span></div>${datasetPreview(s,'Current working data')}<div class="studio-shortcuts">${[['descriptive','Describe sample'],['trends','Show a trend'],['variables','Create a variable'],['merge','Combine datasets'],['history','View changes'],['workflow','Repeat with new files']].map(([id,label])=>`<button type="button" class="secondary" data-prepare="${id}">${label}</button>`).join('')}</div><div class="studio-form"><label class="studio-check"><input id="spDuplicates" type="checkbox">Remove duplicate rows</label><label class="studio-check"><input id="spMissing" type="checkbox">Remove rows with any missing cell</label><label class="studio-check"><input id="spEmpty" type="checkbox">Remove completely empty columns</label><label>Outliers (optional)<select id="spOutlier"><option value="none">Keep all values</option><option value="remove">Remove rows outside 1.5×IQR</option><option value="winsorize">Cap values at 1.5×IQR fences</option></select></label><label>Outlier variable<select id="spMetric">${opts(s.cols.filter(c=>s.types[c]==='numeric'))}</select></label></div><p class="studio-note">Missing-row removal checks every current column and runs before empty-column removal. An empty column can therefore remove all rows; the preview will stop you. Outlier fences are recalculated on each new file.</p>${button('spPreview','Preview preparation','primary')}<div id="spResult"></div>`;
 mount.querySelectorAll('[data-prepare]').forEach(b=>b.onclick=()=>{if(['descriptive','trends'].includes(b.dataset.prepare)){const tools=document.getElementById('legacyTools');if(tools)tools.open=true;bridge.open(b.dataset.prepare);document.getElementById('dataQuickConfig')?.scrollIntoView({behavior:'smooth'});}else navigate(b.dataset.prepare);});let prepared=null;
 for(const id of ['spDuplicates','spMissing','spEmpty','spOutlier','spMetric'])$(id).onchange=()=>{prepared=null;$('spResult').innerHTML='';};
 $('spPreview').onclick=()=>run(()=>{if(s.headerSuggestion)throw Error('Review and apply the detected headers above first.');const steps=[];if($('spDuplicates').checked||$('spMissing').checked||$('spEmpty').checked)steps.push({kind:'clean',options:{removeDuplicates:$('spDuplicates').checked,removeMissing:$('spMissing').checked,dropEmpty:$('spEmpty').checked,fields:s.cols.slice()}});if($('spOutlier').value!=='none')steps.push({kind:'outliers',metric:$('spMetric').value,action:$('spOutlier').value});if(!steps.length)throw Error('Choose a preparation action first.');let next=s;const counts=[];for(const step of steps){const before=next.rows.length;next=W.applyStep(next,step);counts.push(step.kind+': '+before+' → '+next.rows.length+' rows');if(!next.rows.length)throw Error('This selection removes every row. Uncheck missing-row removal or inspect empty columns first.');}prepared={revision,steps,next};$('spResult').innerHTML=`<div class="studio-callout"><h4>${s.rows.length} → ${next.rows.length} rows</h4><p>${counts.map(E).join('<br>')}<br>${s.cols.length} → ${next.cols.length} columns. Original values are retained in the uploaded copy.</p>${datasetPreview(next,'Prepared data preview')}${button('spApply','Apply and record these steps','primary')}</div>`;
 $('spApply').onclick=()=>run(()=>{if(!prepared||prepared.revision!==revision)throw Error('Data changed. Preview again.');const p=prepared;for(const step of p.steps)mutate('Prepare data',JSON.stringify(step),()=>bridge.set(W.applyStep(state(),step)),step);message('Preparation recorded. Use Repeat with new files to run these same rules again.');});});
 }
 function renderSensitivity(){
 const s=state();$('studioSensitivity').innerHTML=`<details ${sensitivityResult?'open':''}><summary>What changes if…? Check a decision</summary><p>Compare a saved model with one explicit alternative. Working data stays unchanged; this does not select a “best” model.</p><div class="studio-form"><label>Baseline model<select id="ssModel">${models.map(m=>`<option value="${E(m.id)}">${E(m.name)} · saved revision ${m.revision}</option>`).join('')}</select></label><label>Decision<select id="ssKind"><option value="outliers">Exclude IQR outliers</option><option value="period">Use a different date range</option><option value="predictors">Change explanatory variables</option></select></label></div><div id="ssOptions"></div>${button('ssRun','Compare this decision','primary')}<div id="ssResult">${sensitivityResult?sensitivityHTML(sensitivityResult):''}</div></details>`;
 const options=()=>{const kind=$('ssKind').value;$('ssOptions').innerHTML=kind==='outliers'?`<label>Screening variable<select id="ssMetric">${opts(s.cols.filter(c=>s.types[c]==='numeric'))}</select></label>`:kind==='period'?`<div class="studio-form"><label>Date column<select id="ssTime">${opts(s.cols)}</select></label><label>From (inclusive)<input id="ssStart" type="date"></label><label>To (inclusive)<input id="ssEnd" type="date"></label></div>`:`<div class="data-variable-list">${s.cols.filter(c=>s.types[c]==='numeric').map(c=>`<label><input type="checkbox" class="ssX" value="${E(c)}">${E(c)}</label>`).join('')}</div><p>Baseline and alternative will use the same complete observations.</p>`;};$('ssKind').onchange=options;options();$('ssRun').disabled=!models.length;
 $('ssRun').onclick=()=>run(()=>{const chosen=models.find(m=>m.id===$('ssModel').value);if(!chosen)throw Error('Save a baseline model first.');const kind=$('ssKind').value,options={kind,metric:$('ssMetric')?.value,time:$('ssTime')?.value,start:$('ssStart')?.value,end:$('ssEnd')?.value,xs:[...mount.querySelectorAll('.ssX:checked')].map(el=>el.value)};for(const c of [chosen.spec.y,...chosen.spec.xs])if(!s.cols.includes(c))throw Error('Baseline variable is missing: '+c);sensitivityResult=null;$('ssResult').innerHTML='';const result=W.sensitivity(s.rows,chosen.spec,options);sensitivityResult={...result,revision,name:chosen.name};$('ssResult').innerHTML=sensitivityHTML(sensitivityResult);});
 }
 function sensitivityHTML(r){return `<div class="studio-callout"><h4>Effect of ${E(r.options.kind)} · data revision ${r.revision}</h4><p>Both fits were calculated on current working data. ${E(r.detail)}</p><p>N: ${r.baseline.n} → ${r.variant.n} · ${r.removed} baseline rows removed · ${r.added} rows added. Original baseline N before sample alignment: ${r.originalN}.</p><div class="data-table-scroll"><table class="data-result-table"><thead><tr><th>Term</th><th>Baseline</th><th>Alternative</th><th>Change</th></tr></thead><tbody>${r.deltas.map(d=>`<tr><th>${E(d.name)}</th><td>${F(d.before)}</td><td>${F(d.after)}</td><td>${F(d.delta)}</td></tr>`).join('')}<tr><th>R²</th><td>${F(r.baseline.r2)}</td><td>${F(r.variant.r2)}</td><td>${F(r.baseline.r2==null||r.variant.r2==null?null:r.variant.r2-r.baseline.r2)}</td></tr></tbody></table></div><p>This is a sensitivity check, not a causal test or a recommendation to delete observations. A larger R² on a different sample does not establish a better model.</p></div>`;}
 function workflowRecipe(){return {format:'dayrixa-workflow',version:1,appVersion:C.VERSION,name:project,columns:bridge.original().cols.slice(),steps:JSON.parse(JSON.stringify(recipe)),models:models.map(m=>({name:m.name,spec:JSON.parse(JSON.stringify(m.spec))})),comparison:comparison?{common:comparison.common,models:comparison.models.map(m=>({name:m.name,spec:m.spec}))}:null,sensitivity:sensitivityResult?{spec:sensitivityResult.spec,options:sensitivityResult.options}:null};}
 function renderWorkflow(){
 const active=replayRecipe||workflowRecipe(),slots=active.steps.filter(s=>s.kind==='merge');
 $('studioBody').innerHTML=`<div class="studio-section-title"><h3>Repeat with new files</h3><span>Preview first. Replace only after review.</span></div><p>Recorded rules run in order, then saved model definitions are refitted. Files and old results are not embedded in a workflow.</p><div class="studio-actions">${button('swSave','Download workflow JSON')}<label>Load a workflow<input id="swLoad" type="file" accept=".json"></label>${button('swCurrent','Use this project’s steps')}</div><ol>${active.steps.map(s=>`<li><strong>${E(s.kind)}</strong> ${E(W.describeStep(s))}</li>`).join('')||'<li>No preparation steps recorded. Only saved model definitions will run.</li>'}</ol><p>${active.models.length} model definitions will be refitted. Old saved coefficients are never reused. Any saved comparison and latest sensitivity settings run again too, including their fixed date bounds.</p><div class="studio-form"><label>New primary dataset<input id="swPrimary" type="file" accept=".csv,.xlsx,.xls"></label>${slots.map((s,i)=>`<label>New file for ${E(s.name||s.slot)}<input id="swRight${i}" type="file" accept=".csv,.xlsx,.xls"></label>`).join('')}</div><p id="swFiles">${E(replayInput?.name||'Choose a primary file.')} ${slots.map(s=>E(replayFiles[s.slot]?.name||'Awaiting '+s.slot)).join(' · ')}</p><div class="studio-actions">${button('swPreview','Run and preview','primary')}</div><div id="swResult"></div>`;
 $('swSave').onclick=()=>run(()=>download(filename()+'_workflow.json',JSON.stringify(active,null,2),'application/json'));
 $('swCurrent').onclick=()=>{replayRecipe=null;replayInput=null;replayFiles={};replayResult=null;renderWorkflow();};
 $('swLoad').onchange=e=>run(async()=>{const f=e.target.files[0];if(!f)return;if(f.size>2*1024*1024)throw Error('Workflow file limit: 2 MB.');const r=W.validateRecipe(JSON.parse(await f.text()));replayRecipe=r;replayInput=null;replayFiles={};replayResult=null;renderWorkflow();});
 const choose=(id,slot)=>{$(id).onchange=e=>run(async()=>{const f=e.target.files[0];if(!f)return;const startRevision=revision,startSource=source,data=await bridge.readDataset(f);if(revision!==startRevision||source!==startSource)throw Error('Project changed during file reading. Choose the file again.');if(slot)replayFiles[slot]=data;else replayInput=data;replayResult=null;if(page==='workflow')renderWorkflow();});};choose('swPrimary');slots.forEach((s,i)=>choose('swRight'+i,s.slot));
 $('swPreview').onclick=()=>run(()=>{replayResult=null;$('swResult').innerHTML='';if(!replayInput)throw Error('Choose the new primary dataset.');const result=W.replay(active,replayInput,replayFiles);replayResult={...result,baseRevision:revision,recipe:JSON.parse(JSON.stringify(active)),input:replayInput};$('swResult').innerHTML=`<div class="studio-callout"><h4>New run: ${result.state.rows.length} rows · ${result.models.length} fitted models</h4><table class="data-result-table"><thead><tr><th>Step</th><th>Rows before</th><th>Rows after</th></tr></thead><tbody>${result.audit.map(a=>`<tr><td>${a.step}. ${E(a.kind)}</td><td>${a.before}</td><td>${a.after}</td></tr>`).join('')}</tbody></table>${result.models.map(m=>`<h4>${E(m.name)}</h4>${modelSummary(m)}${modelTable(m)}`).join('')}${result.comparison?comparisonHTML({...result.comparison,revision:'preview'}):''}${result.sensitivityResult?sensitivityHTML({...result.sensitivityResult,revision:'preview'}):''}${datasetPreview(result.state,'New working data')}<p>Applying starts a new project run. Save the current project first if you want to retain its undo history and earlier results.</p><label class="studio-check"><input id="swConfirm" type="checkbox">I checked column meanings, units, time conventions, step counts and new results; replace the current run.</label>${button('swApply','Use this run','primary')}</div>`;
 $('swApply').disabled=true;$('swConfirm').onchange=()=>{$('swApply').disabled=!$('swConfirm').checked;};$('swApply').onclick=()=>run(()=>{if(!replayResult||replayResult.baseRevision!==revision||!$('swConfirm').checked)throw Error('Working data changed or review is incomplete. Run the preview again.');const r=replayResult;bridge.set(r.state);bridge.setOriginal(r.input);reset(r.input.name||'Workflow run');recipe=r.recipe.steps;derived=recipe.filter(s=>s.kind==='variables').flatMap(s=>s.variables.map(v=>({...v,unit:v.unit||'',time:v.time||'',entity:v.entity||'',revision:1})));models=r.models.map((m,i)=>({...m,id:'replay_'+Date.now()+'_'+i,revision:1,at:now()}));comparison=r.comparison?{...r.comparison,revision,models:r.comparison.models.map(m=>({...m,revision}))}:null;sensitivityResult=r.sensitivityResult?{...r.sensitivityResult,revision}:null;entry('Replay workflow',JSON.stringify({steps:r.audit,source:r.input.name}),r.input,state());snapshots=[{revision,state:recordState()}];cursor=0;page='models';render();message('New run applied. Every model was recomputed from the new files.');});});
 }
 function latexReport(title,note){
 const output=models.map(m=>({...m,name:m.name+(m.revision!==revision?' [earlier data revision]':'')}));if(comparison)output.push(...comparison.models.map(m=>({...m,name:'Comparison: '+m.name})));if(sensitivityResult){output.push({...sensitivityResult.baseline,name:'Sensitivity baseline',revision},{...sensitivityResult.variant,name:'Sensitivity alternative',revision});}
 if(!output.length)throw Error('Save a model or create a comparison first.');const extra=[note,comparison?'Comparison sample: '+(comparison.common?'common complete rows':'model-specific rows'):'',sensitivityResult?sensitivityResult.detail+' Decision: '+sensitivityResult.options.kind+'; screening variable: '+(sensitivityResult.options.metric||'not used'):''].filter(Boolean).join('\n');return W.latex(title,output,{source,revision,notes:extra,steps:recipe});
 }

 function renderVariables(){
 const s=state(),numeric=s.cols.filter(c=>s.types[c]==='numeric');
 $('studioBody').innerHTML=`<div class="studio-section-title"><h3>Create a variable</h3><span>Preview → review missing values → apply</span></div><div class="studio-form"><label>New variable name<input id="svName" placeholder="Excess_RI" maxlength="80"></label><label>Unit / description<input id="svUnit" placeholder="e.g. percentage points" maxlength="180"></label><label>Start from a template<select id="svTemplate">${opts(['Custom','Excess return / difference','Ratio','Natural logarithm','One-observation lag','Percentage change','Positive-value indicator'])}</select></label><label>Insert variable<select id="svInsert"><option value="">Choose a column…</option>${opts(s.cols)}</select></label><label class="studio-wide">Formula<input id="svFormula" placeholder="RI - Rf" autocomplete="off" spellcheck="false"></label><label>Time column (required for lags)<select id="svTime">${opts(s.cols,'',true)}</select></label><label>Entity / panel ID (optional)<select id="svEntity">${opts(s.cols,'',true)}</select></label></div><p class="studio-note">Use aliases or full names in backticks. Supported: + − * / ^, comparisons, log(x), sqrt(x), abs(x), exp(x), lag(x, 1), diff(x, 1), pct_change(x, 1). Lag means previous observed row within each entity after time sorting, not necessarily the previous calendar month. Missing inputs and invalid calculations become missing values. Created columns store the previewed values; later edits to source columns do not automatically recalculate them. Recreate a variable when its inputs change.</p><div class="studio-actions">${button('svPreview','Preview variable','primary')}</div><div id="svPreviewResult"></div><details><summary>Available variables and aliases</summary><div class="data-table-scroll"><table class="data-result-table"><thead><tr><th>Variable</th><th>Alias</th><th>Type</th></tr></thead><tbody>${s.cols.map(c=>`<tr><td>${E(c)}</td><td>${E(C.alias(c))}</td><td>${E(s.types[c])}</td></tr>`).join('')}</tbody></table></div></details>${derived.length?`<h4>Created variables</h4><ul>${derived.map(v=>`<li><b>${E(v.name)}</b> = ${E(v.formula)} · ${E(v.unit)} · revision ${v.revision}</li>`).join('')}</ul>`:''}`;
 $('svInsert').onchange=e=>{if(e.target.value)$('svFormula').value+='`'+e.target.value+'`';};
 $('svTemplate').onchange=e=>{const a=numeric[0]?'`'+numeric[0]+'`':'X',b=numeric[1]?'`'+numeric[1]+'`':'Y';const values={'Custom':'','Excess return / difference':a+' - '+b,'Ratio':a+' / '+b,'Natural logarithm':'log('+a+')','One-observation lag':'lag('+a+', 1)','Percentage change':'pct_change('+a+', 1)','Positive-value indicator':a+' > 0'};$('svFormula').value=values[e.target.value];};
 for(const id of ['svName','svFormula','svUnit','svTime','svEntity'])$(id).oninput=()=>{preview=null;$('svPreviewResult').innerHTML='';};
 $('svPreview').onclick=()=>run(()=>{if(s.headerSuggestion)throw Error('Confirm the detected column headers before creating variables.');const name=$('svName').value.trim(),formula=$('svFormula').value.trim(),unit=$('svUnit').value.trim(),time=$('svTime').value,entity=$('svEntity').value;
 if(!/^[\p{L}_][\p{L}\p{N}_]{0,79}$/u.test(name))throw Error('Use a name starting with a letter, then letters, numbers or underscores.');if(s.cols.some(c=>c.toLowerCase()===name.toLowerCase()))throw Error('A variable with this name already exists.');if(time&&entity===time)throw Error('Time and entity columns must differ.');
 const values=C.evaluateExpression(formula,s.rows,s.cols,{time,entity}),missing=values.filter(v=>v==null).length;preview={name,formula,unit,time,entity,values,revision};
 $('svPreviewResult').innerHTML=`<div class="studio-callout"><strong>${E(name)}</strong><p>${values.length-missing} numeric values · ${missing} missing / undefined values. No data has changed yet.</p><table class="data-result-table"><thead><tr><th>Working row</th><th>New value</th></tr></thead><tbody>${values.slice(0,8).map((v,i)=>`<tr><td>${i+1}</td><td>${F(v)}</td></tr>`).join('')}</tbody></table>${button('svApply','Apply to working data','primary')}</div>`;
 $('svApply').onclick=()=>run(()=>{if(!preview||preview.revision!==revision)throw Error('Data changed. Preview the formula again.');const p=preview;mutate('Create variable',p.name+' = '+p.formula,()=>{const current=state();derived.push({name:p.name,formula:p.formula,unit:p.unit,time:p.time,entity:p.entity,revision:serial+1});const nextCols=[...current.cols,p.name],nextRows=current.rows.map((r,i)=>({...r,[p.name]:p.values[i]}));bridge.set({...current,cols:nextCols,rows:nextRows,rawGrid:[nextCols,...nextRows.map(r=>nextCols.map(c=>r[c]))],rawMerges:[],headerSuggestion:null});},{kind:'variables',variables:[{name:p.name,formula:p.formula,unit:p.unit,time:p.time,entity:p.entity}]});message('Variable created. It is now available to every analysis.');});
 });
 }
 function datasetPreview(s,label){return `<details><summary>${E(label)} · ${s.rows.length} rows × ${s.cols.length} columns — inspect first 5 rows</summary><div class="data-table-scroll"><table class="data-result-table"><thead><tr>${s.cols.slice(0,10).map(c=>`<th>${E(c)}</th>`).join('')}</tr></thead><tbody>${s.rows.slice(0,5).map(r=>`<tr>${s.cols.slice(0,10).map(c=>`<td>${E(r[c])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${s.cols.length>10?'<p>Preview shows the first 10 columns. All columns remain available.</p>':''}</details>`;}
 function renderMerge(){
 const left=state();
 $('studioBody').innerHTML=`<div class="studio-section-title"><h3>Merge datasets</h3><span>Inspect both → choose keys → validate → apply</span></div><p>Add columns from a second dataset. The first dataset is your current working data. Existing values are preserved; colliding column names receive a _right suffix.</p>${datasetPreview(left,'First dataset: '+source)}<label class="studio-file">Choose second dataset (CSV / Excel; first sheet, first nonempty row as header)<input id="sjFile" type="file" accept=".csv,.xlsx,.xls"></label><div id="sjControls"></div>`;
 $('sjFile').onchange=e=>run(async()=>{const file=e.target.files[0];if(!file)return;const startRevision=revision;const loaded=await bridge.readDataset(file);if(revision!==startRevision)throw Error('Working data changed during upload. Choose the second file again.');secondary=loaded;mergePreview=null;if(page==='merge')renderMergeControls();});
 if(secondary)renderMergeControls();
 }
 function renderMergeControls(){
 const left=state(),right=secondary,suggestions=C.suggestMerge(left,right);
 $('sjControls').innerHTML=`${datasetPreview(right,'Second dataset: '+right.name)}${right.headerSuggestion?'<p class="data-warning">Possible multi-row header in the second file. Check the preview and prepare a single header row before merging if these column names are incorrect.</p>':''}<h4>Suggested keys</h4><p class="studio-note">Suggestions use column names, key uniqueness and observed matches. They are candidates, not proof that the datasets describe the same entities or dates.</p><div class="studio-guide">${suggestions.map((p,i)=>`<article><h4>${E(p.label)}</h4><p>${p.keys.map(k=>`${E(k.left)} ↔ ${E(k.right)} (${E(k.mode)})`).join('<br>')}</p><p>${p.diagnostics.matched} / ${left.rows.length} left rows match · ${p.diagnostics.rightDuplicateKeys} duplicate right keys${p.diagnostics.blocked?' · BLOCKED':''}</p><button type="button" data-merge-suggestion="${i}" class="secondary">Use these keys</button></article>`).join('')||'<p>No confident key candidates from column names. Map the keys manually below.</p>'}</div><h4>Join settings</h4><div class="studio-form"><label>First dataset: key 1<select id="sjL1">${opts(left.cols)}</select></label><label>Second dataset: key 1<select id="sjR1">${opts(right.cols)}</select></label><label>Key 1 matching<select id="sjMode1">${mergeModes()}</select></label><label>Join type<select id="sjHow"><option value="left">Keep all first-dataset rows (left join)</option><option value="inner">Keep only matched first-dataset rows (inner join)</option></select></label><label>First dataset: key 2 (optional)<select id="sjL2">${opts(left.cols,'',true)}</select></label><label>Second dataset: key 2 (optional)<select id="sjR2">${opts(right.cols,'',true)}</select></label><label>Key 2 matching<select id="sjMode2">${mergeModes()}</select></label></div><p class="studio-note">Panel + panel: use entity ID and time. Panel + a market series unique by date: use time. Panel + company attributes unique by company: use entity ID. Exact matching trims outer spaces but preserves case and leading zeros. Dates accept YYYY-MM-DD, YYYY-MM, YYYY or US MM/DD/YYYY as appropriate; ambiguous slash dates are interpreted as US dates. Month/year matching does not aggregate multiple observations. Blank or invalid keys never match.</p><div class="studio-actions">${button('sjPreview','Validate and preview merge','primary')}</div><div id="sjResult"></div>`;
 const ids=['sjL1','sjR1','sjL2','sjR2','sjMode1','sjMode2','sjHow'];for(const id of ids)$(id).onchange=()=>{mergePreview=null;$('sjResult').innerHTML='';};
 mount.querySelectorAll('[data-merge-suggestion]').forEach(b=>b.onclick=()=>{const p=suggestions[+b.dataset.mergeSuggestion];for(let i=1;i<=2;i++){const k=p.keys[i-1];$('sjL'+i).value=k?.left||'';$('sjR'+i).value=k?.right||'';$('sjMode'+i).value=k?.mode||'exact';}mergePreview=null;$('sjResult').innerHTML='';message('Keys selected. Review their meaning, then validate the merge.');});
 $('sjPreview').onclick=()=>run(()=>{
 mergePreview=null;$('sjResult').innerHTML='';const keys=[{left:$('sjL1').value,right:$('sjR1').value,mode:$('sjMode1').value}];if($('sjL2').value||$('sjR2').value){if(!$('sjL2').value||!$('sjR2').value)throw Error('Choose the second key on both datasets, or leave both empty.');keys.push({left:$('sjL2').value,right:$('sjR2').value,mode:$('sjMode2').value});}
 const config={keys,how:$('sjHow').value},d=C.inspectMerge(left,right,config),safeCandidate=suggestions.find(p=>!p.diagnostics.blocked&&p.diagnostics.matched>0&&p.keys.length>keys.length);
 const metrics=[['Relationship',d.relationship],['First / second dataset rows',d.leftRows+' / '+d.rightRows],['Matched first-dataset rows',d.matched],['Unmatched first-dataset rows',d.unmatched],['Unused second-dataset rows',d.unusedRight],['Missing / invalid key rows: first / second',d.invalidLeft+' / '+d.invalidRight],['Repeated keys: first / second',d.leftDuplicateKeys+' / '+d.rightDuplicateKeys],['Expected output rows',d.expectedRows??'Blocked']];
 $('sjResult').innerHTML=`<div class="studio-callout"><h4>${d.blocked?'Merge blocked — duplicate keys in second dataset':'Merge checks complete'}</h4><table class="data-result-table"><tbody>${metrics.map(([k,v])=>`<tr><th>${E(k)}</th><td>${E(v)}</td></tr>`).join('')}</tbody></table>${d.blocked?`<p>Add the missing key (often entity + date), or resolve the duplicates in the second file. DAYRIXA will not choose an arbitrary match or multiply rows.</p>${safeCandidate?`<p>A candidate using ${safeCandidate.keys.map(k=>E(k.left)+' + '+E(k.right)).join('; ')} has unique right-side keys. Check whether those columns identify the same entities in both files.</p>${button('sjFixKeys','Review the suggested compound key')}`:''}<ul>${d.duplicateRightSamples.map(x=>`<li>Key ${E(x.key.join(' / '))}: ${x.count} rows; first working-row numbers ${x.rows.join(', ')}</li>`).join('')}</ul>`:`<p>${config.how==='inner'?d.unmatched+' unmatched first-dataset rows will be removed.':'All first-dataset rows will be retained in their original order.'} ${d.matched===0?'Warning: no keys match. Added values will all be missing.':''}</p><div id="sjPreviewTable"></div><label class="studio-check"><input id="sjConfirm" type="checkbox">I reviewed the key meanings, date frequency and unmatched counts.</label>${button('sjApply','Apply validated merge','primary')}`}${button('sjAudit','Download match audit CSV')}</div>`;
 $('sjAudit').onclick=()=>run(()=>{const matrix=[['Dataset','Working row (1-based)','Status',...keys.map((k,i)=>'Key '+(i+1))]];d.unmatchedLeft.forEach(i=>matrix.push(['First',i+1,'Unmatched',...keys.map(k=>left.rows[i][k.left])]));d.unusedRightIndexes.forEach(i=>matrix.push(['Second',i+1,'Unused',...keys.map(k=>right.rows[i][k.right])]));download(filename()+'_merge_unmatched.csv',C.csv(matrix),'text/csv;charset=utf-8');});
 if(d.blocked){if(safeCandidate)$('sjFixKeys').onclick=()=>{safeCandidate.keys.forEach((k,i)=>{$('sjL'+(i+1)).value=k.left;$('sjR'+(i+1)).value=k.right;$('sjMode'+(i+1)).value=k.mode;});mergePreview=null;$('sjResult').innerHTML='';message('Suggested keys selected. Confirm their meaning and validate again.');};return;}
 const result=C.mergeDatasets(left,right,config);mergePreview={revision,config,result,rightName:right.name};
 $('sjPreviewTable').innerHTML=`<p>Validated: ${result.rows.length} output rows; each retained first-dataset row appears exactly once.</p><p>Added columns: ${result.columns.map(c=>`${E(c.source)} → ${E(c.target)}`).join('; ')}</p>${datasetPreview(result,'Merged preview')}`;
 $('sjApply').disabled=true;$('sjConfirm').onchange=()=>{$('sjApply').disabled=!$('sjConfirm').checked;};
 $('sjApply').onclick=()=>run(()=>{if(!$('sjConfirm').checked)throw Error('Review and acknowledge the merge preview.');if(!mergePreview||mergePreview.revision!==revision)throw Error('Working data changed. Validate the merge again.');const p=mergePreview;if(!p.result.rows.length)throw Error('This merge would produce an empty dataset. Change the keys or use a left join.');
 const detail=JSON.stringify({secondDataset:p.rightName,join:p.config.how,keys:p.config.keys,matched:p.result.diagnostics.matched,unmatched:p.result.diagnostics.unmatched,unusedRight:p.result.diagnostics.unusedRight,outputRows:p.result.rows.length,rowCountValidated:true,columns:p.result.columns});
 mutate('Merge datasets',detail,()=>{bridge.set({...state(),rows:p.result.rows,cols:p.result.cols,rawGrid:[p.result.cols,...p.result.rows.map(r=>p.result.cols.map(c=>r[c]))],rawMerges:[],headerSuggestion:null});},{kind:'merge',slot:'merge_'+(recipe.length+1),name:p.rightName,rightColumns:secondary.cols.slice(),config:p.config});mergePreview=null;message('Merge applied and row count verified. The operation is recorded in Data history and can be undone.');});
 });
 }
 function mergeModes(){return '<option value="exact">Exact text / ID</option><option value="day">Calendar day</option><option value="month">Calendar month</option><option value="year">Calendar year</option>';}

 function modelSummary(m){const rows=[['Observations (N)',m.n],['Excluded incomplete rows',m.excluded],['R²'+(m.spec.intercept?'':' (uncentered)'),F(m.r2)],['Adjusted R²',F(m.adj)],['Residual degrees of freedom',m.df],['Residual standard error',F(m.rmse)],['Standard errors',m.spec.seType],['Intercept',m.spec.intercept?'Included':'Excluded']];return `<table class="data-result-table"><thead><tr><th>Model statistic</th><th>Value</th></tr></thead><tbody>${rows.map(([k,v])=>`<tr><th>${E(k)}</th><td>${E(v)}</td></tr>`).join('')}</tbody></table>`;}
 function modelTable(m){return `<table class="data-result-table"><thead><tr><th>Term</th><th>Coefficient</th><th>Mode</th><th>SE</th><th>t</th></tr></thead><tbody>${m.terms.map(t=>`<tr><td>${E(t.name)}</td><td>${F(t.beta)}</td><td>${t.fixed?'Fixed by user':'Estimated'}</td><td>${F(t.se)}</td><td>${F(t.t)}</td></tr>`).join('')}</tbody></table>`;}
 function specFromControls(withFixed=true){const s=state();if(s.headerSuggestion)throw Error('Confirm the detected column headers before fitting a model.');let y=$('smY').value,xs=[...mount.querySelectorAll('.smX:checked')].map(el=>el.value),formula=$('smFormula').value.trim();if(formula){const sides=formula.split('~');if(sides.length!==2)throw Error('Use Y ~ X1 + X2.');y=C.resolve(sides[0].trim().replace(/^`|`$/g,''),s.cols);xs=sides[1].split('+').map(v=>C.resolve(v.trim().replace(/^`|`$/g,''),s.cols));}const fixed={};if(withFixed)mount.querySelectorAll('.smFixed').forEach(el=>{if(el.value.trim()!==''){const term=el.dataset.term,value=Number(el.value);if(!Number.isFinite(value))throw Error('Fixed coefficients must be finite numbers.');if(!(xs.includes(term)||(term==='Intercept'&&$('smIntercept').checked)))throw Error('Model changed: refresh coefficient settings.');fixed[term]=value;}});return {y,xs,intercept:$('smIntercept').checked,seType:$('smSE').value,fixed};}
 function renderModels(){
 const s=state(),numeric=s.cols.filter(c=>s.types[c]==='numeric');
 $('studioBody').innerHTML=`<div class="studio-section-title"><h3>Model lab</h3><span>Fit → save → compare on a shared sample</span></div><div id="smCAPM"></div><div class="studio-form"><label>Model name<input id="smName" maxlength="100" value="Model ${models.length+1}"></label><label>Dependent variable (Y)<select id="smY">${opts(numeric)}</select></label><div class="studio-wide"><span>Explanatory variables (X)</span><div class="data-variable-list">${numeric.map(c=>`<label><input class="smX" type="checkbox" value="${E(c)}"> ${E(c)}</label>`).join('')}</div></div><details class="studio-wide"><summary>Advanced model settings</summary><div class="studio-form"><label class="studio-wide">Optional formula (overrides selections)<input id="smFormula" placeholder="RI ~ Rm + Rf + Rb"></label><label>Standard errors<select id="smSE"><option value="OLS">Conventional OLS</option><option value="HC1">Heteroskedasticity-robust HC1</option></select></label><label class="studio-check"><input type="checkbox" id="smIntercept" checked>Include intercept</label></div></details></div><p class="studio-note">OLS estimates association, not causation. HC1 allows heteroskedasticity but does not adjust for serial correlation or clustered observations. Fixed effects, clustered and HAC errors are not implemented.</p><details><summary>Fix a coefficient to a known value</summary><div class="studio-actions">${button('smCoefficients','Set / refresh coefficient restrictions')}</div><div id="smCoefficientFields"></div></details><p class="studio-note">By default all coefficients are estimated. Use coefficient restrictions only when you intend to impose a known value. Formulas accept Y ~ X1 + X2; create transformed variables first, or use the CAPM assistant.</p><div class="studio-actions">${button('smRun','Fit model','primary')}</div><div id="smResult"></div><div id="studioSensitivity"></div><h4>Saved models</h4><div class="studio-model-list">${models.length?models.map(m=>`<label><input class="smSaved" type="checkbox" value="${E(m.id)}" ${m.revision===revision?'checked':''}><span><strong>${E(m.name)}</strong><small>${E(m.spec.y)} ~ ${E(m.spec.xs.join(' + '))}</small><small>N=${m.n} · ${E(m.spec.seType)} · revision ${m.revision} ${m.revision!==revision?'· earlier data version':''}</small></span><button type="button" data-remove-model="${E(m.id)}" aria-label="Remove ${E(m.name)}">×</button></label>`).join(''):'<p>No saved models yet. Fit a model and save its result.</p>'}</div><div class="studio-actions"><label>Comparison sample<select id="smSample"><option value="common">Common complete rows (recommended)</option><option value="available">Available rows for each model</option></select></label>${button('smCompare','Refit selected models on current data')}</div><div id="smComparison">${comparison?comparisonHTML(comparison):''}</div>`;
 const preferred=a=>numeric.find(c=>C.alias(c).toLowerCase()===a.toLowerCase())||(a==='RI'?numeric.find(c=>C.alias(c)==='Rl'):null)||numeric[0];
 $('smCAPM').innerHTML=`<details><summary>CAPM assistant — build excess returns</summary><p>Ri − Rf = alpha + beta × (Rm − Rf) + error. Select period returns, not price/index levels. All three inputs must have the same frequency and units. An annualized bill yield is not automatically a monthly return.</p><div class="studio-form"><label>Asset / portfolio return (Ri)<select id="scAsset">${opts(numeric,preferred('RI'))}</select></label><label>Market return (Rm)<select id="scMarket">${opts(numeric,preferred('Rm'))}</select></label><label>Risk-free period return (Rf)<select id="scRiskFree">${opts(numeric,preferred('Rf'))}</select></label></div><label>Risk-free input definition<select id="scFrequency"><option value="">Choose the definition…</option><option value="period">Return for the same period as Ri and Rm</option><option value="annual">Annualized yield / rate</option><option value="unknown">I am not sure</option></select></label><p class="studio-note">Monthly observations do not establish that Rf is a monthly return. If Rf is annualized, prepare a period-return column using the appropriate quotation convention first.</p><label class="studio-check"><input id="scUnits" type="checkbox">I checked return definitions, period alignment and matching units.</label>${button('scBuild','Create CAPM variables and set model')}</details>`;
 $('scBuild').onclick=()=>run(()=>{if(s.headerSuggestion)throw Error('Confirm the detected column headers before configuring CAPM.');if($('scFrequency').value!=='period')throw Error('CAPM needs a risk-free return for the same period and in the same units as the asset and market returns. Is your Rf an annualized bill yield? Confirm its quotation convention and create a period-return column first; no automatic division by 12 is applied.');if(!$('scUnits').checked)throw Error('Check the return definitions, frequency and units first.');const asset=$('scAsset').value,market=$('scMarket').value,rf=$('scRiskFree').value;if(new Set([asset,market,rf]).size!==3)throw Error('Choose three distinct return columns.');const current=state();const unique=base=>{let name=base,n=2;while(current.cols.includes(name))name=base+'_'+n++;return name;};const y=unique('CAPM_AssetExcess'),x=unique('CAPM_MarketExcess');
 mutate('Create CAPM variables',JSON.stringify({asset,market,riskFree:rf,y,x,unitsConfirmed:true}),()=>{const nextRows=current.rows.map(r=>{const a=C.number(r[asset]),m=C.number(r[market]),f=C.number(r[rf]);return {...r,[y]:Number.isFinite(a)&&Number.isFinite(f)?a-f:null,[x]:Number.isFinite(m)&&Number.isFinite(f)?m-f:null};}),nextCols=[...current.cols,y,x];for(const [name,col]of [[y,asset],[x,market]])derived.push({name,formula:'`'+col+'` - `'+rf+'`',unit:'Same as input returns',time:'',entity:'',revision:serial+1});bridge.set({...current,rows:nextRows,cols:nextCols,rawGrid:[nextCols,...nextRows.map(r=>nextCols.map(c=>r[c]))],rawMerges:[],headerSuggestion:null});},{kind:'variables',variables:[[y,asset],[x,market]].map(([name,col])=>({name,formula:'`'+col+'` - `'+rf+'`',unit:'Same-period return',time:'',entity:''})),context:{model:'CAPM',riskFreeDefinition:'same-period return',unitsConfirmed:true}});
 $('smName').value='CAPM';$('smFormula').value='';$('smY').value=y;$('smIntercept').checked=true;mount.querySelectorAll('.smX').forEach(el=>{el.disabled=el.value===y;el.checked=el.value===x;});message('CAPM is configured. Fit to estimate alpha and beta, or open coefficient settings to fix alpha (e.g. 0) or beta. The model pools all working rows; filter to one asset when needed.');});
 $('smCoefficients').onclick=()=>run(()=>{const spec=specFromControls(false),names=spec.intercept?['Intercept',...spec.xs]:spec.xs;if(!spec.xs.length)throw Error('Choose the model variables first.');$('smCoefficientFields').innerHTML=`<table class="data-result-table"><thead><tr><th>Term</th><th>Fixed value (blank = estimate)</th></tr></thead><tbody>${names.map((name,i)=>`<tr><th>${E(name)} (${name==='Intercept'?'alpha':'beta '+(spec.intercept?i:i+1)})</th><td><input class="smFixed" data-term="${E(name)}" type="number" step="any" placeholder="Estimate from data" aria-label="Fixed coefficient for ${E(name)}"></td></tr>`).join('')}</tbody></table><p>Fixed values are restrictions, not starting guesses. SE and t are not estimated for fixed terms. Refresh these settings after changing your model.</p>`;});

 renderSensitivity();
 const sync=()=>mount.querySelectorAll('.smX').forEach(el=>{el.disabled=el.value===$('smY').value;if(el.disabled)el.checked=false;});$('smY').onchange=sync;sync();
 $('smRun').onclick=()=>run(()=>{lastFit=null;$('smResult').innerHTML='';const spec=specFromControls(),fit=C.fit(s.rows,spec);lastFit={...fit,name:$('smName').value.trim()||'Untitled model',revision,at:now(),id:'m'+Date.now()+Math.random().toString(16).slice(2)};
 $('smResult').innerHTML=`<div class="studio-callout"><h4>${E(lastFit.name)}</h4>${modelSummary(fit)}<p>${E(spec.y)} ~ ${E(spec.xs.join(' + '))} · ${E(spec.seType)} errors</p>${modelTable(fit)}${button('smSave','Save this fitted model','primary')}<p>Save this model to examine the effect of outliers, periods or other predictors.</p></div>`;
 $('smSave').onclick=()=>run(()=>{if(!lastFit||lastFit.revision!==revision)throw Error('Fit the model again on the current data.');if(models.length>=20)throw Error('This prototype supports 20 saved models per project.');models.push(lastFit);lastFit=null;render();message('Model saved with its data revision and sample.');});
 });
 mount.querySelectorAll('[data-remove-model]').forEach(b=>b.onclick=e=>{e.preventDefault();models=models.filter(m=>m.id!==b.dataset.removeModel);comparison=null;render();});
 $('smCompare').onclick=()=>run(()=>{comparison=null;$('smComparison').innerHTML='';const ids=[...mount.querySelectorAll('.smSaved:checked')].map(x=>x.value),chosen=models.filter(m=>ids.includes(m.id));if(chosen.some(m=>[m.spec.y,...m.spec.xs].some(c=>!s.cols.includes(c))))throw Error('A saved model uses a column that is absent from the current dataset. Restore or rebuild the variable first.');const common=$('smSample').value==='common',fits=C.compare(s.rows,chosen.map(m=>m.spec),common);comparison={revision,common,at:now(),models:fits.map((m,i)=>({...m,name:chosen[i].name,revision,sourceModel:chosen[i].id}))};$('smComparison').innerHTML=comparisonHTML(comparison);});
 }
 function comparisonHTML(c){const fits=c.models,terms=[...new Set(fits.flatMap(m=>m.terms.map(t=>t.name)))],same=fits.every(m=>JSON.stringify(m.ids)===JSON.stringify(fits[0].ids));
 const stat=(label,fn)=>`<tr><th>${label}</th>${fits.map(m=>`<td>${E(fn(m))}</td>`).join('')}</tr>`;
 return `<div class="studio-callout"><h4>Model comparison · data revision ${c.revision}</h4><p>${same?'Exactly the same observations in every model.':'Samples differ: changes in fit may reflect different observations.'} ${c.common?'Common complete-case sample.':'Model-specific complete-case samples.'} All selected models were refitted on the current working data.</p><div class="data-table-scroll"><table class="data-result-table"><thead><tr><th>Term / statistic</th>${fits.map(m=>`<th>${E(m.name)}</th>`).join('')}</tr></thead><tbody>${terms.map(term=>`<tr><th>${E(term)}</th>${fits.map(m=>{const t=m.terms.find(t=>t.name===term);return `<td>${t?`${F(t.beta)}<small>${t.fixed?'Fixed by user':'SE '+F(t.se)+' · t '+F(t.t)}</small>`:'—'}</td>`;}).join('')}</tr>`).join('')}${stat('N',m=>m.n)}${stat('Excluded rows',m=>m.excluded)}${stat('R²',m=>F(m.r2))}${stat('Adjusted R²',m=>F(m.adj))}${stat('Residual SE',m=>F(m.rmse))}${stat('Residual df',m=>m.df)}${stat('Errors',m=>m.spec.seType)}${stat('Intercept',m=>m.spec.intercept?'Yes':'No')}${stat('R² definition',m=>m.spec.intercept?'Centered':'Uncentered')}</tbody></table></div><p class="studio-note">A larger R² does not establish causality or out-of-sample performance. Centered and uncentered R² are not directly comparable. Coefficients are shown with standard errors and t statistics, without significance stars.</p></div>`;
 }
 function renderHistory(){
 $('studioBody').innerHTML=`<div class="studio-section-title"><h3>Data history</h3><span>Current revision ${revision}</span></div><p>Undo/redo retains up to 12 recent changes during this session. The audit log below retains every recorded operation. Saving a project preserves the current data and log; the undo buffer restarts when reopened.</p><div class="data-table-scroll"><table class="data-result-table"><thead><tr><th>Time (UTC)</th><th>Action</th><th>Detail</th><th>Rows</th><th>Columns</th><th>Revision</th></tr></thead><tbody>${journal.slice().reverse().map(j=>`<tr><td>${E(j.at)}</td><td>${E(j.action)}</td><td>${E(j.detail)}</td><td>${j.rowsBefore} → ${j.rowsAfter}</td><td>${j.columnsBefore} → ${j.columnsAfter}</td><td>${j.revision}</td></tr>`).join('')}</tbody></table></div>`;
 }
 function download(name,text,type='text/plain;charset=utf-8'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const filename=()=>project.replace(/[^\p{L}\p{N}_-]+/gu,'_').slice(0,80)||'DAYRIXA_study';
 function comparisonCSV(c){const fits=c.models,terms=[...new Set(fits.flatMap(m=>m.terms.map(t=>t.name)))],matrix=[['Variable / statistic',...fits.map(m=>m.name)]];for(const term of terms)for(const [key,label] of [['beta','Coefficient'],['se','SE'],['t','t statistic'],['fixed','Fixed by user']])matrix.push([term+' — '+label,...fits.map(m=>m.terms.find(t=>t.name===term)?.[key]??'')]);for(const key of ['n','df','r2','adj','rmse','excluded'])matrix.push([key,...fits.map(m=>m[key]??'')]);matrix.push(['Sample policy',...fits.map(()=>c.common?'Common complete rows':'Model-specific complete rows')],['Data revision',...fits.map(()=>c.revision)],['Standard errors',...fits.map(m=>m.spec.seType)],['Dependent variable',...fits.map(m=>m.spec.y)],['Formula',...fits.map(m=>m.spec.y+' ~ '+m.spec.xs.join(' + '))],['Intercept',...fits.map(m=>m.spec.intercept?'Yes':'No')]);return C.csv(matrix);}
 function reportHTML(title,note,figure){const s=state();return `<!doctype html><html lang="en"><meta charset="utf-8"><title>${E(title)}</title><style>body{font:15px/1.5 Georgia,serif;color:#172432;max-width:1050px;margin:40px auto;padding:24px}h1,h2,h3,h4,th{font-family:Arial,sans-serif}table{border-collapse:collapse;width:100%;margin:16px 0}th,td{border-bottom:1px solid #ccd4da;padding:9px;text-align:left}small{display:block;color:#465460}p{max-width:950px}img{max-width:100%;background:#102331}button{padding:10px}footer{border-top:1px solid #ccd4da;margin-top:30px}@media print{button{display:none}body{margin:0;padding:0}tr{break-inside:avoid}}</style><body><button onclick="window.print()">Print / Save as PDF</button><h1>${E(title)}</h1><p>DAYRIXA Research Studio ${C.VERSION} · exported ${E(now())}</p><h2>Data and method</h2><p>Source: ${E(source)}. Working data: ${s.rows.length} rows × ${s.cols.length} columns. Revision ${revision}. Missing numeric observations are excluded separately for each fitted model unless common-sample comparison is selected. Percent strings are parsed in percentage-point units, without division by 100. Conventional OLS and HC1 are supported; neither adjusts for autocorrelation or clustering.</p><h2>Research notes</h2><p style="white-space:pre-wrap">${E(note||'No research notes provided.')}</p><h2>Derived variables</h2><ul>${derived.map(d=>`<li>${E(d.name)} = ${E(d.formula)}; unit: ${E(d.unit)}; time: ${E(d.time)}; entity: ${E(d.entity)}; created revision ${d.revision}</li>`).join('')||'<li>None.</li>'}</ul>${comparison?`<h2>Comparison</h2>${comparisonHTML(comparison)}`:'<p>No comparison was created for this export.</p>'}${sensitivityResult?'<h2>Decision sensitivity</h2>'+sensitivityHTML(sensitivityResult):''}<h2>Saved models</h2>${models.map(m=>`<h3>${E(m.name)}</h3><p>Revision ${m.revision}${m.revision!==revision?' (earlier data version; not refitted)':''}; ${E(m.spec.y)} ~ ${E(m.spec.xs.join(' + '))}; intercept ${m.spec.intercept?'included':'excluded'}; ${E(m.spec.seType)} errors; N=${m.n}; R²=${F(m.r2)}${m.spec.intercept?'':' (uncentered)'}; adjusted R²=${F(m.adj)}; residual df=${m.df}; residual SE=${F(m.rmse)}.</p>${modelSummary(m)}${modelTable(m)}`).join('')||'<p>No saved models.</p>'}${figure?`<h2>Current chart</h2><p>${E(bridge.resultText())}</p><img alt="Current analysis chart" src="${figure}">`:''}<h2>Data audit log</h2><table><thead><tr><th>Time (UTC)</th><th>Action</th><th>Detail</th><th>Rows before → after</th><th>Revision</th></tr></thead><tbody>${journal.map(j=>`<tr><td>${E(j.at)}</td><td>${E(j.action)}</td><td>${E(j.detail)}</td><td>${j.rowsBefore} → ${j.rowsAfter}</td><td>${j.revision}</td></tr>`).join('')}</tbody></table><footer>© 2026 DAYRIXA. All rights reserved.<br>Created and developed by Iman Malekikhajkolaei.<br>Exploratory research output; analyst review is required before publication.</footer></body></html>`;}
 function exportProject(){return {format:'dayrixa-research-project',version:1,appVersion:C.VERSION,project,reportTitle,researchNotes,source,revision,serial,state:recordState(),original:bridge.original(),journal,models,comparison,sensitivity:sensitivityResult};}
 function validateState(s){if(!s||!Array.isArray(s.rows)||!Array.isArray(s.cols)||s.cols.length>2000||s.rows.length>1000000||new Set(s.cols).size!==s.cols.length||!s.cols.every(c=>typeof c==='string'&&c.length<=500))throw Error('Invalid project dataset.');for(const r of s.rows){if(!r||typeof r!=='object'||Array.isArray(r))throw Error('Invalid data row.');for(const c of s.cols){const v=r[c];if(v!=null&&!['string','number','boolean'].includes(typeof v))throw Error('Project cells must be text, numbers, booleans or missing.');}}return s;}
 function importProject(p){if(p?.format!=='dayrixa-research-project'||p.version!==1)throw Error('Unsupported project file.');validateState(p.state);validateState(p.original);if(!Array.isArray(p.journal)||p.journal.length>100000||!Array.isArray(p.models)||p.models.length>20)throw Error('Invalid project history or models.');
 if(!Number.isInteger(p.revision)||!Number.isInteger(p.serial)||p.revision<1||p.serial<p.revision)throw Error('Invalid revision information.');
 for(const m of p.models){if(!m.spec||!Array.isArray(m.spec.xs)||!m.spec.xs.every(x=>typeof x==='string')||typeof m.spec.y!=='string'||!Array.isArray(m.terms)||!m.terms.every(t=>typeof t.name==='string'&&Number.isFinite(t.beta)&&(Number.isFinite(t.se)||(t.fixed===true&&t.se===null&&t.t===null)))||!Array.isArray(m.ids)||!Number.isInteger(m.n))throw Error('Invalid saved model.');}
 for(const j of p.journal){if(!j||!['at','action','detail'].every(k=>typeof j[k]==='string')||!['revision','rowsBefore','rowsAfter','columnsBefore','columnsAfter'].every(k=>Number.isInteger(j[k])&&j[k]>=0))throw Error('Invalid audit record.');}
 for(const m of p.models){if(typeof m.id!=='string'||typeof m.name!=='string'||!Number.isInteger(m.revision)||!['OLS','HC1'].includes(m.spec.seType)||typeof m.spec.intercept!=='boolean'||!m.ids.every(Number.isInteger)||!['n','df','excluded'].every(k=>Number.isInteger(m[k])&&m[k]>=0)||!['r2','adj','rmse','sse'].every(k=>m[k]===null||Number.isFinite(m[k])))throw Error('Invalid model metadata.');}
 if(p.state.derived&&(!Array.isArray(p.state.derived)||!p.state.derived.every(v=>v&&['name','formula','unit','time','entity'].every(k=>typeof v[k]==='string')&&Number.isInteger(v.revision))))throw Error('Invalid variable history.');
 for(const data of [p.state,p.original]){if(data.rawGrid&&!Array.isArray(data.rawGrid))throw Error('Invalid raw data.');if(data.rawMerges&&!Array.isArray(data.rawMerges))throw Error('Invalid merge metadata.');data.headerSuggestion=null;}

 if(p.state.recipe)W.validateRecipe({format:'dayrixa-workflow',version:1,columns:p.original.cols,steps:p.state.recipe,models:[]});
 const restoredSensitivity=p.sensitivity?{...W.sensitivity(p.state.rows,p.sensitivity.spec,p.sensitivity.options),revision:p.revision}:null;
 let restoredComparison=null;
 if(p.comparison){const c=p.comparison;if(c.revision!==p.revision||typeof c.common!=='boolean'||!Array.isArray(c.models)||c.models.length<2||c.models.length>20||c.models.some(m=>!m.spec||typeof m.name!=='string'||!Array.isArray(m.spec.xs)||[m.spec.y,...m.spec.xs].some(x=>!p.state.cols.includes(x))))throw Error('Invalid model comparison.');const fits=C.compare(p.state.rows,c.models.map(m=>m.spec),c.common);restoredComparison={revision:p.revision,common:c.common,at:now(),models:fits.map((m,i)=>({...m,name:c.models[i].name,revision:p.revision}))};}
 secondary=null;mergePreview=null;reportTitle=String(p.reportTitle||'').slice(0,200);researchNotes=String(p.researchNotes||'').slice(0,50000);project=String(p.project||'Restored study').slice(0,120);source=String(p.source||'Project file');revision=p.revision;serial=p.serial;models=p.models;journal=p.journal;bridge.setOriginal(p.original);setState(p.state);if(!Array.isArray(p.state.recipe)&&p.journal.some(j=>!['Import','Undo','Redo'].includes(j.action)))recipe=[{kind:'unsupported',reason:'This project predates executable workflows. Record its preparation again.'}];sensitivityResult=restoredSensitivity;snapshots=[{revision,state:recordState()}];cursor=0;comparison=restoredComparison;page='guide';render();message('Project reopened. Saved model results are preserved; refit to independently verify them. Undo starts from this restored state.');
 }
 function renderExport(){
 $('studioBody').innerHTML=`<div class="studio-section-title"><h3>Research outputs</h3><span>Data + method + provenance</span></div><div class="studio-form"><label class="studio-wide">Report title<input id="seTitle" value="${E(reportTitle||project)}" maxlength="200"></label><label class="studio-wide">Research question / notes<textarea id="seNotes" rows="4" placeholder="Explain the research question, units and interpretation. Your notes are included verbatim in the report.">${E(researchNotes)}</textarea></label><label class="studio-check"><input id="seFigure" type="checkbox">Include current chart in report</label></div><div class="studio-guide"><article><h4>Research report</h4><p>Formatted HTML with models, comparison, variable formulas and history. Open it in your browser, then Print → Save as PDF.</p>${button('seReport','Download report')}${button('seLatex','Download LaTeX (.tex)')}<p>Compile .tex with XeLaTeX or LuaLaTeX. Includes saved models, current comparison and the latest sensitivity check.</p></article><article><h4>Tables and data</h4><p>CSV files for Excel, R or Python. Comparison includes coefficients, SE, t and model specifications.</p>${button('seCompare','Comparison CSV')}${button('seData','Working data CSV')}${button('seHistory','History CSV')}${button('sePNG','Current chart PNG')}</article><article><h4>Continue later</h4><p>A project file contains your data, original working copy, created variables, model results and history. Keep it private if the source data is private.</p>${button('seProject','Save project JSON')}${button('seWorkflow','Repeat with new files')}<label class="studio-file">Reopen project<input id="seImport" type="file" accept=".json,application/json"></label></article></div>`;
 $('seWorkflow').onclick=()=>{page='workflow';render();};$('seLatex').onclick=()=>run(()=>download(filename()+'_results.tex',latexReport($('seTitle').value,$('seNotes').value),'application/x-tex;charset=utf-8'));
 $('seTitle').onchange=()=>{reportTitle=$('seTitle').value;};$('seNotes').onchange=()=>{researchNotes=$('seNotes').value;};
 $('seReport').onclick=()=>run(()=>{let figure=null;if($('seFigure').checked){figure=bridge.figure();if(!figure)throw Error('There is no current chart. Run a chart first or uncheck this option.');}download(filename()+'_report.html',reportHTML($('seTitle').value,$('seNotes').value,figure),'text/html;charset=utf-8');});
 $('seCompare').disabled=!comparison;$('seCompare').onclick=()=>run(()=>download(filename()+'_comparison.csv',comparisonCSV(comparison),'text/csv;charset=utf-8'));
 $('seData').onclick=()=>run(()=>{const s=state();download(filename()+'_data.csv',C.csv([s.cols,...s.rows.map(r=>s.cols.map(c=>r[c]))]),'text/csv;charset=utf-8');});
 $('seHistory').onclick=()=>run(()=>download(filename()+'_history.csv',C.csv([['Time UTC','Action','Detail','Revision','Rows before','Rows after'],...journal.map(j=>[j.at,j.action,j.detail,j.revision,j.rowsBefore,j.rowsAfter])]),'text/csv;charset=utf-8'));
 $('seProject').onclick=()=>run(()=>download(filename()+'.dayrixa.json',JSON.stringify(exportProject()),'application/json'));
 $('sePNG').onclick=()=>run(()=>{const image=bridge.figure();if(!image)throw Error('There is no current chart. Run a chart first.');const a=document.createElement('a');a.href=image;a.download=filename()+'_chart.png';document.body.appendChild(a);a.click();a.remove();});
 $('seImport').onchange=e=>run(async()=>{const f=e.target.files[0];if(!f)return;if(f.size>100*1024*1024)throw Error('Project import limit is 100 MB.');importProject(JSON.parse(await f.text()));});
 }
 return {reset,render,mutate,commit,capture:recordState,undo,exportProject,importProject,reportHTML,comparisonCSV,workflowRecipe,latexReport,getState:()=>({source,revision,serial,journal,models,derived,comparison,page,recipe,sensitivityResult}),setPage:p=>{page=p;render();}};
};
})(window);
