'use strict';
const $=id=>document.getElementById(id), names={ridge:'Ridge',boost:'Boosted trees',mlp:'Neural network'};
let dataset=null,rows=[],result=null,worker=null,isDemo=false,chartMode='price',selectedFile='',marketMeta=null,marketController=null;
const pct=x=>Number.isFinite(x)?(x*100).toFixed(2)+'%':'—';
function error(message){$('error').textContent=message;$('error').hidden=!message;}
function resetResult(){result=null;$('export').disabled=true;$('evalContent').hidden=true;$('evalEmpty').hidden=false;$('decision').className='panel decision empty';$('decisionTitle').textContent='Ready to analyze';$('decisionReason').textContent='The previous result was cleared after data or settings changed. Run the analysis again.';['pred','risk','model'].forEach(id=>$(id).textContent='—');$('asof').textContent=rows.length?'Through '+rows.at(-1).date:'Waiting for data';draw();}
function busy(on){$('run').disabled=on||rows.length<900;$('cancel').hidden=!on;['symbol','horizon','cost','file','demo','adjusted','marketQuery','exchange','marketResults','searchMarket','fetchMarket'].forEach(id=>$(id).disabled=on||(id==='symbol'&&!dataset));}
function load(text,label,demo,meta=null){
 marketMeta=meta;$('marketIdentity').textContent=meta?meta.symbol+' · '+meta.exchange+' · '+meta.currency:demo?'Synthetic data · No real market':'Uploaded file · Market and currency unverified';if(!meta){$('instrument').hidden=true;$('marketStatus').textContent='';}
 try{const parsed=EntryEngine.csv(text);dataset=parsed;isDemo=demo;selectedFile=label;$('symbol').replaceChildren(...Object.keys(parsed.groups).map(symbol=>{const op=document.createElement('option');op.value=symbol;op.textContent=demo?'DEMO · Synthetic data':symbol;return op;}));$('adjusted').checked=parsed.adjusted;choose();error('');}catch(e){dataset=null;rows=[];$('symbol').replaceChildren();$('fileInfo').textContent='File rejected';resetResult();busy(false);quality();error(e.message);}
}
function quality(){const box=$('dataQuality');box.hidden=!rows.length;if(!rows.length){box.textContent='';return;}const age=(Date.now()-Date.parse(rows.at(-1).date))/86400000;box.textContent=[rows.length>=900?'Enough rows to begin testing.':'History is too short; '+(900-rows.length)+' more trading days are required.',dataset.adjusted?'Adj Close detected; adjustments are applied consistently to OHLC.':$('adjusted').checked?'Price adjustment is based on your confirmation.':'Adjustment is unverified. Confirm it only if you know the OHLC prices are consistently adjusted.',age>7?'The data is stale. Historical testing is available, but it cannot support an entry signal for today.':'',isDemo?'This data is synthetic and cannot support a real trading decision.':''].filter(Boolean).join(' ');}
function choose(){rows=dataset.groups[$('symbol').value];$('fileInfo').textContent=selectedFile+' · '+rows.length.toLocaleString('en-US')+' rows · '+rows[0].date+' to '+rows.at(-1).date;busy(false);resetResult();quality();}
$('file').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;clearMarketData();marketError('');error('');if(f.size>12000000){error('File size must be below 12 MB.');return;}if(!/\.(csv|tsv)$/i.test(f.name)){error('Only CSV and TSV are supported. In Excel, use Save As and select CSV UTF-8.');return;}busy(true);$('progress').textContent='Reading and checking the file…';try{load(await f.text(),f.name,false);}catch(e){error('Could not read the file.');}finally{busy(false);$('progress').textContent='';e.target.value='';}});
$('symbol').onchange=choose;['horizon','cost','adjusted'].forEach(id=>$(id).addEventListener('change',()=>{resetResult();quality();}));
$('demo').onclick=()=>load(EntryEngine.demoCSV(),'Synthetic example for learning the tool',true);
function download(content,file,type){const u=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=u;a.download=file;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
$('template').onclick=()=>download('Date,Symbol,Open,High,Low,Close,Adj Close,Volume\n','dayrixa-price-template.csv','text/csv');
$('run').onclick=()=>{
 error('');if(rows.length<900){error('At least 900 trading days are required.');return;}const cost=Number($('cost').value);if($('cost').value===''||!Number.isFinite(cost)||cost<0||cost>200){error('Costs must be between 0 and 200 basis points.');return;}
 resetResult();busy(true);$('progress').textContent='Preparing data and chronological splits…';
 try{worker=new Worker('worker.js');worker.onmessage=({data})=>{if(data.stage)$('progress').textContent=data.stage==='latest'?'Computing the latest forecast…':'Training and evaluating '+names[data.stage]+'…';if(data.error){error(data.error);finish();}if(data.result){result=data.result;render();finish();}};worker.onerror=()=>{error('Analysis stopped unexpectedly. Reload the page.');finish();};worker.postMessage({rows,options:{horizon:Number($('horizon').value),costBps:cost,demo:isDemo,adjusted:dataset.adjusted||$('adjusted').checked}});}catch(e){error('The browser could not start the analysis engine.');finish();}
};
function finish(){if(worker)worker.terminate();worker=null;busy(false);$('progress').textContent='';}
$('cancel').onclick=()=>{finish();$('progress').textContent='Analysis cancelled.';};
function td(text,cls){const e=document.createElement('td');e.textContent=text;if(cls)e.className=cls;return e;}
function render(){const r=result;$('decision').className='panel decision '+r.status;$('decisionTitle').textContent={enter:'Initial model conditions met; confirmation needed',wait:'Wait for stronger evidence',avoid:'Entry conditions not met',invalid:'Cannot assess entry conditions',demo:'Demo using synthetic data'}[r.status];$('decisionReason').textContent=r.reason;$('asof').textContent='Data through '+r.lastDate+' · '+r.h+' sessions';$('pred').textContent=pct(r.prediction);$('risk').textContent=pct(r.latestVol);$('model').textContent=names[r.winner];$('evalEmpty').hidden=true;$('evalContent').hidden=false;$('export').disabled=false;
 const metrics=[['Net strategy return',pct(r.sim.total)],['Buy and hold',pct(r.sim.buyHold)],['Maximum drawdown',pct(r.sim.drawdown)],['Closed trades',r.sim.trades.length.toLocaleString('en-US')]];$('metrics').replaceChildren(...metrics.map(([label,val])=>{const e=document.createElement('div'),s=document.createElement('span'),b=document.createElement('strong');s.textContent=label;b.textContent=val;e.append(s,b);return e;}));
 $('modelRows').replaceChildren(...r.summaries.map(s=>{const tr=document.createElement('tr');tr.append(td(names[s.type]),td((Math.sqrt(s.valMSE)*100).toFixed(3),'num'),td((Math.sqrt(s.testMSE)*100).toFixed(3),'num'),td(pct(s.skill),'num'),td(s.type===r.winner?'Validation selection':'—'));return tr;}));
 $('split').replaceChildren(...[['train','Training'],['validation','Validation'],['test','Test']].map(([key,label])=>{const d=document.createElement('div'),s=document.createElement('small');d.textContent=label+' · '+r.split[key][2]+' samples';s.textContent=r.split[key][0]+' — '+r.split[key][1];d.append(s);return d;}));
 $('tradeRows').replaceChildren(...r.sim.trades.map(t=>{const tr=document.createElement('tr');tr.append(td(t.entryDate),td(t.exitDate),td(pct(t.pred),'num'),td(pct(t.net),'num'));return tr;}));if(!r.sim.trades.length){const tr=document.createElement('tr'),cell=td('No trades met the fixed entry rule during this period.');cell.colSpan=4;tr.append(cell);$('tradeRows').append(tr);}draw();
}
$('export').onclick=()=>{if(result)download(JSON.stringify({app:'DAYRIXA Asset Pricing Analysis',symbol:$('symbol').value,source:selectedFile,market:marketMeta,synthetic:isDemo,adjustmentConfirmed:dataset.adjusted||$('adjusted').checked,generatedAt:new Date().toISOString(),limitations:'Experimental single-asset adaptation; not a paper replication or validated production signal. Test metrics are not statistically independent. Daily Yahoo history when fetched; not realtime.',...result},null,2),'dayrixa-entry-report.json','application/json');};
document.querySelectorAll('[data-chart]').forEach(b=>b.onclick=()=>{chartMode=b.dataset.chart;document.querySelectorAll('[data-chart]').forEach(x=>x.classList.toggle('selected',x===b));draw();});
const ns='http://www.w3.org/2000/svg';function svgEl(tag,attrs){const e=document.createElementNS(ns,tag);for(const [k,v]of Object.entries(attrs||{}))e.setAttribute(k,v);return e;}
function draw(){$('chartDetail').textContent=chartMode==='equity'?'Select a point to compare strategy and buy-and-hold equity.':'Select a point on the chart to inspect its price.';$('legendEntries').hidden=chartMode!=='price';$('chartTitle').textContent=chartMode==='equity'?'Growth of one unit of capital in the test period':'Price and simulated entries';$('legendBH').hidden=chartMode!=='equity';$('legendMain').textContent=chartMode==='equity'?'Test strategy':'Adjusted price';const container=$('chart');container.replaceChildren();if(!rows.length){container.textContent='Upload valid data first.';return;}let data;if(chartMode==='equity'){if(!result){const p=document.createElement('div');p.className='chart-empty';p.textContent='Run the analysis to view performance.';container.append(p);return;}data=result.sim.curve.map(r=>({date:r.date,y:r.equity,bh:r.buyHold}));}else{data=rows.map((r,i)=>({date:r.date,y:r.close,index:i}));}
 $('chartTitle').textContent=chartMode==='equity'?'Growth of one unit of capital in the test period':'Price and simulated entries';$('chartSub').textContent=isDemo?'Synthetic data · This chart does not represent real market performance.':chartMode==='equity'?'Entry and exit costs included; cash earns zero return.':'Entry at the next session open after a signal; exit after the fixed horizon.';$('legendMain').textContent=chartMode==='equity'?'Test strategy':'Adjusted price';$('legendBH').hidden=chartMode!=='equity';
 const w=900,h=280,left=12,right=68,top=15,bottom=32,values=data.flatMap(d=>chartMode==='equity'?[d.y,d.bh]:[d.y]);let min=Math.min(...values),max=Math.max(...values);const pad=(max-min)*.12||1;min-=pad;max+=pad;const x=i=>left+i/(data.length-1)*(w-left-right),y=v=>top+(max-v)/(max-min)*(h-top-bottom),s=svgEl('svg',{viewBox:`0 0 ${w} ${h}`,preserveAspectRatio:'none','aria-hidden':'true'});
 for(let j=0;j<5;j++){const val=min+(max-min)*j/4,yy=y(val);s.append(svgEl('line',{x1:left,x2:w-right,y1:yy,y2:yy,stroke:'#26374b','stroke-width':1}));const t=svgEl('text',{x:w-right+10,y:yy+4,fill:'#a7b9cb','font-size':12,'font-family':'Arial'});t.textContent=val.toFixed(2);s.append(t);}
 for(const f of [0,.5,1]){const i=Math.round(f*(data.length-1)),t=svgEl('text',{x:x(i),y:h-5,fill:'#a7b9cb','font-size':12,'font-family':'Arial','text-anchor':f===0?'start':f===1?'end':'middle'});t.textContent=data[i].date;s.append(t);}
 if(result&&chartMode==='price'){const ti=data.findIndex(d=>d.date===result.split.test[0]);if(ti>=0){s.append(svgEl('rect',{x:x(ti),y:top,width:w-right-x(ti),height:h-top-bottom,fill:'#67e0c2',opacity:.04}));s.append(svgEl('line',{x1:x(ti),x2:x(ti),y1:top,y2:h-bottom,stroke:'#67e0c2','stroke-dasharray':'4 4',opacity:.6}));}}
 function line(key,color){s.append(svgEl('path',{d:data.map((d,i)=>(i?'L':'M')+x(i).toFixed(2)+','+y(d[key]).toFixed(2)).join(' '),fill:'none',stroke:color,'stroke-width':2,'vector-effect':'non-scaling-stroke'}));}if(chartMode==='equity')line('bh','#8896a7');line('y','#78aaff');
 if(result&&chartMode==='price'){for(const t of result.sim.trades){const i=t.entry;s.append(svgEl('circle',{cx:x(i),cy:y(data[i].y),r:4,fill:'#67e0c2',stroke:'#0b1726','stroke-width':2}));}}
 const cursor=svgEl('line',{y1:top,y2:h-bottom,stroke:'#d1e2f1','stroke-dasharray':'3 4',visibility:'hidden'});s.append(cursor);const inspect=evt=>{const rect=s.getBoundingClientRect(),index=clampIndex(Math.round(((evt.clientX-rect.left)/rect.width*w-left)/(w-left-right)*(data.length-1)),data.length);cursor.setAttribute('x1',x(index));cursor.setAttribute('x2',x(index));cursor.setAttribute('visibility','visible');const d=data[index],signal=result?.forecasts.find(f=>f.date===d.date);$('chartDetail').textContent=d.date+' · '+(chartMode==='equity'?'Equity: ':'Price: ')+d.y.toFixed(2)+(chartMode==='equity'?' · Buy and hold: '+d.bh.toFixed(2):'')+(signal?' · Forecast that day: '+pct(signal.prediction):'');};s.addEventListener('pointermove',inspect);s.addEventListener('click',inspect);container.append(s);container.setAttribute('aria-label',`${chartMode==='price'?'Price':'Performance'} from ${data[0].date} to ${data.at(-1).date}`);}
function clampIndex(i,n){return Math.max(0,Math.min(n-1,i));}
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 try{Promise.resolve(document.modelContext.registerTool({name:'read_entry_analysis',title:'Read current entry analysis',description:'Read the visible analysis, dates and experimental status. Does not fetch prices or place trades.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(input&&Object.keys(input).length)throw Error('No parameters accepted.');return result?{symbol:$('symbol').value,synthetic:isDemo,status:result.status,reason:result.reason,asOf:result.lastDate,horizon:result.h,forecast:result.prediction,model:result.winner,testReturn:result.sim.total,limitations:'Experimental, not production validated.'}:{status:'no_analysis',message:'Upload data and run the visible analysis first.'};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}

function marketError(message){$('marketError').textContent=message;$('marketError').hidden=!message;}
function marketBusy(on){['marketQuery','exchange','marketResults','searchMarket','fetchMarket','file','demo','symbol','horizon','cost','adjusted'].forEach(id=>$(id).disabled=on||(id==='symbol'&&!dataset));$('cancelMarket').hidden=!on;$('run').disabled=on||rows.length<900;}
function invalidateMarketSelection(){if(marketController)marketController.abort();$('marketResults').replaceChildren();const op=document.createElement('option');op.value='';op.textContent='Entered symbol and selected exchange';$('marketResults').append(op);clearMarketData();}
function clearMarketData(){if(worker)finish();dataset=null;rows=[];marketMeta=null;$('marketIdentity').textContent='Uploaded file · Market and currency unverified';$('symbol').replaceChildren();$('fileInfo').textContent='No file selected';$('instrument').hidden=true;resetResult();busy(false);quality();}
$('marketQuery').addEventListener('input',invalidateMarketSelection);$('exchange').addEventListener('change',invalidateMarketSelection);$('marketResults').addEventListener('change',clearMarketData);
async function marketRequest(url){const response=await fetch(url,{signal:marketController.signal});let data;try{data=await response.json();}catch{throw Error('The data service response could not be read.');}if(!response.ok)throw Error(data.error||'Data download failed.');return data;}
$('searchMarket').onclick=async()=>{if(window.DAYRIXA_OFFLINE)return;const q=$('marketQuery').value.trim();if(q.length<2){marketError('Enter at least two characters of a name or symbol.');return;}clearMarketData();marketController=new AbortController();marketBusy(true);marketError('');$('marketStatus').textContent='Searching Canadian listings…';try{const data=await marketRequest('/api/market/search?q='+encodeURIComponent(q));$('marketResults').replaceChildren();for(const row of data.results){const op=document.createElement('option');op.value=row.symbol;op.textContent=row.symbol+' · '+row.name+' · '+row.exchange+' · '+row.instrumentType;$('marketResults').append(op);}if(!data.results.length){const op=document.createElement('option');op.value='';op.textContent='No results found; enter an exact symbol.';$('marketResults').append(op);}$('marketStatus').textContent=data.results.length?'Select the exact symbol, then download its history.':'No matching Canadian listing found.';}catch(e){marketError(e.name==='AbortError'?'Download cancelled.':e.message);$('marketStatus').textContent='';}finally{marketController=null;marketBusy(false);}};
$('fetchMarket').onclick=async()=>{if(window.DAYRIXA_OFFLINE)return;let symbol=$('marketResults').value||$('marketQuery').value.trim().toUpperCase();if(!/\.(TO|V|NE|CN)$/.test(symbol))symbol+='.'+$('exchange').value;if(!/^[A-Z0-9][A-Z0-9.\-]{0,24}\.(TO|V|NE|CN)$/.test(symbol)){marketError('Enter an exact symbol to download directly. For a company name, search first.');return;}
 clearMarketData();marketController=new AbortController();marketBusy(true);marketError('');error('');$('marketStatus').textContent='Downloading and checking history for '+symbol+'…';let start=false;
 try{const d=await marketRequest('/api/market/history?symbol='+encodeURIComponent(symbol));const csv=['Date,Symbol,Open,High,Low,Close,Adj Close,Volume',...d.rows.map(r=>[r.date,d.symbol,r.open,r.high,r.low,r.close,r.adjClose,r.volume].join(','))].join('\n');const {rows:unused,...meta}=d;load(csv,d.source+' · '+d.symbol,false,meta);const box=$('instrument');box.replaceChildren();const name=document.createElement('b');name.textContent=d.name;const identity=document.createElement('div');identity.textContent=d.symbol+' · '+d.exchange+' · '+d.currency+' · '+d.instrumentType;const dates=document.createElement('small');dates.textContent=d.available+' sessions · '+d.firstDate+' to '+d.lastDate;box.append(name,identity,dates);box.hidden=false;$('marketStatus').textContent='History received; '+d.incomplete+' incomplete sessions and '+d.skipped+' incomplete rows excluded.';if(!d.sufficient){marketError(d.warning+' ('+d.available+' of at least '+d.minimum+' rows)');}else start=true;}catch(e){marketError(e.name==='AbortError'?'Download cancelled.':e.message);$('marketStatus').textContent='';}finally{marketController=null;marketBusy(false);}if(start)$('run').click();};
$('cancelMarket').onclick=()=>marketController?.abort();

if(window.DAYRIXA_OFFLINE){$('onlineSection').hidden=true;}
