'use strict';
const $=id=>document.getElementById(id), names={ridge:'Ridge',boost:'Boosted trees',mlp:'Neural network'};
let dataset=null,rows=[],result=null,worker=null,isDemo=false,chartMode='price',selectedFile='',marketMeta=null,marketController=null;
const pct=x=>Number.isFinite(x)?(x*100).toFixed(2)+'%':'—';
function error(message){$('error').textContent=message;$('error').hidden=!message;}
function resetResult(){result=null;$('export').disabled=true;$('evalContent').hidden=true;$('evalEmpty').hidden=false;$('decision').className='panel decision empty';$('decisionTitle').textContent='آماده بررسی داده';$('decisionReason').textContent='نتیجه قبلی با تغییر داده یا تنظیمات کنار گذاشته شد. بررسی را اجرا کنید.';['pred','risk','model'].forEach(id=>$(id).textContent='—');$('asof').textContent=rows.length?'تا '+rows.at(-1).date:'در انتظار داده';draw();}
function busy(on){$('run').disabled=on||rows.length<900;$('cancel').hidden=!on;['symbol','horizon','cost','file','demo','adjusted','marketQuery','exchange','marketResults','searchMarket','fetchMarket'].forEach(id=>$(id).disabled=on||(id==='symbol'&&!dataset));}
function load(text,label,demo,meta=null){
 marketMeta=meta;$('marketIdentity').textContent=meta?meta.symbol+' · '+meta.exchange+' · '+meta.currency:demo?'داده مصنوعی · بدون بازار واقعی':'فایل شخصی · بازار و ارز تأیید نشده';if(!meta){$('instrument').hidden=true;$('marketStatus').textContent='';}
 try{const parsed=EntryEngine.csv(text);dataset=parsed;isDemo=demo;selectedFile=label;$('symbol').replaceChildren(...Object.keys(parsed.groups).map(symbol=>{const op=document.createElement('option');op.value=symbol;op.textContent=demo?'DEMO · داده مصنوعی':symbol;return op;}));$('adjusted').checked=parsed.adjusted;choose();error('');}catch(e){dataset=null;rows=[];$('symbol').replaceChildren();$('fileInfo').textContent='فایل پذیرفته نشد';resetResult();busy(false);quality();error(e.message);}
}
function quality(){const box=$('dataQuality');box.hidden=!rows.length;if(!rows.length){box.textContent='';return;}const age=(Date.now()-Date.parse(rows.at(-1).date))/86400000;box.textContent=[rows.length>=900?'تعداد ردیف برای شروع آزمون کافی است.':'تاریخچه کوتاه است؛ '+(900-rows.length)+' روز معاملاتی دیگر لازم است.',dataset.adjusted?'ستون Adj Close شناسایی شد؛ تعدیل روی OHLC اعمال می‌شود.':$('adjusted').checked?'تعدیل قیمت‌ها بر اساس تأیید شماست.':'تعدیل مشخص نیست؛ فقط اگر مطمئن هستید گزینه تأیید تعدیل را بزنید.',age>7?'داده قدیمی است؛ آزمون تاریخی ممکن است، اما برای ورود امروز سیگنال معتبر نمی‌گیرد.':'',isDemo?'این داده مصنوعی است و برای تصمیم واقعی استفاده نمی‌شود.':''].filter(Boolean).join(' ');}
function choose(){rows=dataset.groups[$('symbol').value];$('fileInfo').textContent=selectedFile+' · '+rows.length.toLocaleString('fa-IR')+' ردیف · '+rows[0].date+' تا '+rows.at(-1).date;busy(false);resetResult();quality();}
$('file').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;clearMarketData();marketError('');error('');if(f.size>12000000){error('فایل باید کمتر از ۱۲ مگابایت باشد.');return;}if(!/\.(csv|tsv)$/i.test(f.name)){error('فقط CSV و TSV پشتیبانی می‌شوند. در Excel از Save As و CSV UTF-8 استفاده کنید.');return;}busy(true);$('progress').textContent='در حال خواندن و کنترل فایل…';try{load(await f.text(),f.name,false);}catch(e){error('خواندن فایل ناموفق بود.');}finally{busy(false);$('progress').textContent='';e.target.value='';}});
$('symbol').onchange=choose;['horizon','cost','adjusted'].forEach(id=>$(id).addEventListener('change',()=>{resetResult();quality();}));
$('demo').onclick=()=>load(EntryEngine.demoCSV(),'نمونه ساختگی برای آموزش کار با ابزار',true);
function download(content,file,type){const u=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=u;a.download=file;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
$('template').onclick=()=>download('Date,Symbol,Open,High,Low,Close,Adj Close,Volume\n','dayrixa-price-template.csv','text/csv');
$('run').onclick=()=>{
 error('');if(rows.length<900){error('حداقل ۹۰۰ روز معاملاتی برای بررسی لازم است.');return;}const cost=Number($('cost').value);if($('cost').value===''||!Number.isFinite(cost)||cost<0||cost>200){error('هزینه باید بین ۰ و ۲۰۰ واحد پایه باشد.');return;}
 resetResult();busy(true);$('progress').textContent='در حال ساخت داده و تفکیک زمانی…';
 try{worker=new Worker('worker.js');worker.onmessage=({data})=>{if(data.stage)$('progress').textContent=data.stage==='latest'?'محاسبه وضعیت آخرین روز…':'آموزش و ارزیابی '+names[data.stage]+'…';if(data.error){error(data.error);finish();}if(data.result){result=data.result;render();finish();}};worker.onerror=()=>{error('اجرای محاسبه متوقف شد. صفحه را دوباره باز کنید.');finish();};worker.postMessage({rows,options:{horizon:Number($('horizon').value),costBps:cost,demo:isDemo,adjusted:dataset.adjusted||$('adjusted').checked}});}catch(e){error('مرورگر نتوانست موتور محاسبه را اجرا کند.');finish();}
};
function finish(){if(worker)worker.terminate();worker=null;busy(false);$('progress').textContent='';}
$('cancel').onclick=()=>{finish();$('progress').textContent='محاسبه لغو شد.';};
function td(text,cls){const e=document.createElement('td');e.textContent=text;if(cls)e.className=cls;return e;}
function render(){const r=result;$('decision').className='panel decision '+r.status;$('decisionTitle').textContent={enter:'شرایط اولیهٔ مدل برقرار است؛ نیازمند تأیید',wait:'فعلاً صبر کن',avoid:'شرایط ورود مساعد نیست',invalid:'برای ورود قابل ارزیابی نیست',demo:'نمایش آزمایشی با داده مصنوعی'}[r.status];$('decisionReason').textContent=r.reason;$('asof').textContent='داده تا '+r.lastDate+' · '+r.h+' جلسه';$('pred').textContent=pct(r.prediction);$('risk').textContent=pct(r.latestVol);$('model').textContent=names[r.winner];$('evalEmpty').hidden=true;$('evalContent').hidden=false;$('export').disabled=false;
 const metrics=[['بازده خالص استراتژی',pct(r.sim.total)],['خرید و نگهداری',pct(r.sim.buyHold)],['بیشترین افت سرمایه',pct(r.sim.drawdown)],['تعداد معاملات بسته‌شده',r.sim.trades.length.toLocaleString('fa-IR')]];$('metrics').replaceChildren(...metrics.map(([label,val])=>{const e=document.createElement('div'),s=document.createElement('span'),b=document.createElement('strong');s.textContent=label;b.textContent=val;e.append(s,b);return e;}));
 $('modelRows').replaceChildren(...r.summaries.map(s=>{const tr=document.createElement('tr');tr.append(td(names[s.type]),td((Math.sqrt(s.valMSE)*100).toFixed(3),'num'),td((Math.sqrt(s.testMSE)*100).toFixed(3),'num'),td(pct(s.skill),'num'),td(s.type===r.winner?'منتخب اعتبارسنجی':'—'));return tr;}));
 $('split').replaceChildren(...[['train','آموزش'],['validation','اعتبارسنجی'],['test','آزمون']].map(([key,label])=>{const d=document.createElement('div'),s=document.createElement('small');d.textContent=label+' · '+r.split[key][2]+' نمونه';s.textContent=r.split[key][0]+' — '+r.split[key][1];d.append(s);return d;}));
 $('tradeRows').replaceChildren(...r.sim.trades.map(t=>{const tr=document.createElement('tr');tr.append(td(t.entryDate),td(t.exitDate),td(pct(t.pred),'num'),td(pct(t.net),'num'));return tr;}));if(!r.sim.trades.length){const tr=document.createElement('tr'),cell=td('در این دوره معامله‌ای با قاعده ثابت ورود شکل نگرفت.');cell.colSpan=4;tr.append(cell);$('tradeRows').append(tr);}draw();
}
$('export').onclick=()=>{if(result)download(JSON.stringify({app:'DAYRIXA Entry Lab',symbol:$('symbol').value,source:selectedFile,market:marketMeta,synthetic:isDemo,adjustmentConfirmed:dataset.adjusted||$('adjusted').checked,generatedAt:new Date().toISOString(),limitations:'Experimental single-asset adaptation; not a paper replication or validated production signal. Test metrics are not statistically independent. Daily Yahoo history when fetched; not realtime.',...result},null,2),'dayrixa-entry-report.json','application/json');};
document.querySelectorAll('[data-chart]').forEach(b=>b.onclick=()=>{chartMode=b.dataset.chart;document.querySelectorAll('[data-chart]').forEach(x=>x.classList.toggle('selected',x===b));draw();});
const ns='http://www.w3.org/2000/svg';function svgEl(tag,attrs){const e=document.createElementNS(ns,tag);for(const [k,v]of Object.entries(attrs||{}))e.setAttribute(k,v);return e;}
function draw(){$('chartDetail').textContent=chartMode==='equity'?'برای دیدن ارزش سرمایه و خرید و نگهداری، یک نقطه را لمس کنید.':'برای دیدن قیمت، یک نقطه روی نمودار را لمس کنید.';$('legendEntries').hidden=chartMode!=='price';$('chartTitle').textContent=chartMode==='equity'?'رشد یک واحد سرمایه در دوره آزمون':'قیمت و نقاط ورود آزمایشی';$('legendBH').hidden=chartMode!=='equity';$('legendMain').textContent=chartMode==='equity'?'استراتژی آزمون':'قیمت تعدیل‌شده';const container=$('chart');container.replaceChildren();if(!rows.length){container.textContent='ابتدا داده معتبر وارد کنید.';return;}let data;if(chartMode==='equity'){if(!result){const p=document.createElement('div');p.className='chart-empty';p.textContent='برای دیدن عملکرد، ابتدا بررسی مدل‌ها را اجرا کنید.';container.append(p);return;}data=result.sim.curve.map(r=>({date:r.date,y:r.equity,bh:r.buyHold}));}else{data=rows.map((r,i)=>({date:r.date,y:r.close,index:i}));}
 $('chartTitle').textContent=chartMode==='equity'?'رشد یک واحد سرمایه در دوره آزمون':'قیمت و نقاط ورود آزمایشی';$('chartSub').textContent=isDemo?'داده مصنوعی · این نمودار عملکرد واقعی بازار نیست.':chartMode==='equity'?'هزینه ورود و خروج منظور شده؛ وجه نقد بازده صفر دارد.':'ورود در بازشدن جلسه پس از سیگنال؛ خروج پس از افق ثابت.';$('legendMain').textContent=chartMode==='equity'?'استراتژی آزمون':'قیمت تعدیل‌شده';$('legendBH').hidden=chartMode!=='equity';
 const w=900,h=280,left=12,right=68,top=15,bottom=32,values=data.flatMap(d=>chartMode==='equity'?[d.y,d.bh]:[d.y]);let min=Math.min(...values),max=Math.max(...values);const pad=(max-min)*.12||1;min-=pad;max+=pad;const x=i=>left+i/(data.length-1)*(w-left-right),y=v=>top+(max-v)/(max-min)*(h-top-bottom),s=svgEl('svg',{viewBox:`0 0 ${w} ${h}`,preserveAspectRatio:'none','aria-hidden':'true'});
 for(let j=0;j<5;j++){const val=min+(max-min)*j/4,yy=y(val);s.append(svgEl('line',{x1:left,x2:w-right,y1:yy,y2:yy,stroke:'#26374b','stroke-width':1}));const t=svgEl('text',{x:w-right+10,y:yy+4,fill:'#a7b9cb','font-size':12,'font-family':'Arial'});t.textContent=val.toFixed(2);s.append(t);}
 for(const f of [0,.5,1]){const i=Math.round(f*(data.length-1)),t=svgEl('text',{x:x(i),y:h-5,fill:'#a7b9cb','font-size':12,'font-family':'Arial','text-anchor':f===0?'start':f===1?'end':'middle'});t.textContent=data[i].date;s.append(t);}
 if(result&&chartMode==='price'){const ti=data.findIndex(d=>d.date===result.split.test[0]);if(ti>=0){s.append(svgEl('rect',{x:x(ti),y:top,width:w-right-x(ti),height:h-top-bottom,fill:'#67e0c2',opacity:.04}));s.append(svgEl('line',{x1:x(ti),x2:x(ti),y1:top,y2:h-bottom,stroke:'#67e0c2','stroke-dasharray':'4 4',opacity:.6}));}}
 function line(key,color){s.append(svgEl('path',{d:data.map((d,i)=>(i?'L':'M')+x(i).toFixed(2)+','+y(d[key]).toFixed(2)).join(' '),fill:'none',stroke:color,'stroke-width':2,'vector-effect':'non-scaling-stroke'}));}if(chartMode==='equity')line('bh','#8896a7');line('y','#78aaff');
 if(result&&chartMode==='price'){for(const t of result.sim.trades){const i=t.entry;s.append(svgEl('circle',{cx:x(i),cy:y(data[i].y),r:4,fill:'#67e0c2',stroke:'#0b1726','stroke-width':2}));}}
 const cursor=svgEl('line',{y1:top,y2:h-bottom,stroke:'#d1e2f1','stroke-dasharray':'3 4',visibility:'hidden'});s.append(cursor);const inspect=evt=>{const rect=s.getBoundingClientRect(),index=clampIndex(Math.round(((evt.clientX-rect.left)/rect.width*w-left)/(w-left-right)*(data.length-1)),data.length);cursor.setAttribute('x1',x(index));cursor.setAttribute('x2',x(index));cursor.setAttribute('visibility','visible');const d=data[index],signal=result?.forecasts.find(f=>f.date===d.date);$('chartDetail').textContent=d.date+' · '+(chartMode==='equity'?'ارزش سرمایه: ':'قیمت: ')+d.y.toFixed(2)+(chartMode==='equity'?' · خرید و نگهداری: '+d.bh.toFixed(2):'')+(signal?' · پیش‌بینی آن روز: '+pct(signal.prediction):'');};s.addEventListener('pointermove',inspect);s.addEventListener('click',inspect);container.append(s);container.setAttribute('aria-label',`${chartMode==='price'?'قیمت':'عملکرد'} از ${data[0].date} تا ${data.at(-1).date}`);}
function clampIndex(i,n){return Math.max(0,Math.min(n-1,i));}
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 try{Promise.resolve(document.modelContext.registerTool({name:'read_entry_analysis',title:'Read current entry analysis',description:'Read the visible analysis, dates and experimental status. Does not fetch prices or place trades.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(input&&Object.keys(input).length)throw Error('No parameters accepted.');return result?{symbol:$('symbol').value,synthetic:isDemo,status:result.status,reason:result.reason,asOf:result.lastDate,horizon:result.h,forecast:result.prediction,model:result.winner,testReturn:result.sim.total,limitations:'Experimental, not production validated.'}:{status:'no_analysis',message:'Upload data and run the visible analysis first.'};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}

function marketError(message){$('marketError').textContent=message;$('marketError').hidden=!message;}
function marketBusy(on){['marketQuery','exchange','marketResults','searchMarket','fetchMarket','file','demo','symbol','horizon','cost','adjusted'].forEach(id=>$(id).disabled=on||(id==='symbol'&&!dataset));$('cancelMarket').hidden=!on;$('run').disabled=on||rows.length<900;}
function invalidateMarketSelection(){if(marketController)marketController.abort();$('marketResults').replaceChildren();const op=document.createElement('option');op.value='';op.textContent='نماد بالا و بورس انتخاب‌شده';$('marketResults').append(op);clearMarketData();}
function clearMarketData(){if(worker)finish();dataset=null;rows=[];marketMeta=null;$('marketIdentity').textContent='فایل شخصی · بازار و ارز تأیید نشده';$('symbol').replaceChildren();$('fileInfo').textContent='هنوز فایلی انتخاب نشده';$('instrument').hidden=true;resetResult();busy(false);quality();}
$('marketQuery').addEventListener('input',invalidateMarketSelection);$('exchange').addEventListener('change',invalidateMarketSelection);$('marketResults').addEventListener('change',clearMarketData);
async function marketRequest(url){const response=await fetch(url,{signal:marketController.signal});let data;try{data=await response.json();}catch{throw Error('پاسخ سرویس دریافت داده قابل‌خواندن نیست.');}if(!response.ok)throw Error(data.error||'دریافت داده ناموفق بود.');return data;}
$('searchMarket').onclick=async()=>{if(window.DAYRIXA_OFFLINE)return;const q=$('marketQuery').value.trim();if(q.length<2){marketError('حداقل دو نویسه از نام یا نماد وارد کنید.');return;}clearMarketData();marketController=new AbortController();marketBusy(true);marketError('');$('marketStatus').textContent='در حال جستجوی نمادهای کانادایی…';try{const data=await marketRequest('/api/market/search?q='+encodeURIComponent(q));$('marketResults').replaceChildren();for(const row of data.results){const op=document.createElement('option');op.value=row.symbol;op.textContent=row.symbol+' · '+row.name+' · '+row.exchange+' · '+row.instrumentType;$('marketResults').append(op);}if(!data.results.length){const op=document.createElement('option');op.value='';op.textContent='نتیجه‌ای پیدا نشد؛ نماد دقیق وارد کنید.';$('marketResults').append(op);}$('marketStatus').textContent=data.results.length?'نماد دقیق را انتخاب کنید، سپس تاریخچه را دریافت کنید.':'نماد کانادایی مطابق پیدا نشد.';}catch(e){marketError(e.name==='AbortError'?'دریافت لغو شد.':e.message);$('marketStatus').textContent='';}finally{marketController=null;marketBusy(false);}};
$('fetchMarket').onclick=async()=>{if(window.DAYRIXA_OFFLINE)return;let symbol=$('marketResults').value||$('marketQuery').value.trim().toUpperCase();if(!/\.(TO|V|NE|CN)$/.test(symbol))symbol+='.'+$('exchange').value;if(!/^[A-Z0-9][A-Z0-9.\-]{0,24}\.(TO|V|NE|CN)$/.test(symbol)){marketError('برای دریافت مستقیم، نماد دقیق وارد کنید. برای نام شرکت ابتدا جستجو را بزنید.');return;}
 clearMarketData();marketController=new AbortController();marketBusy(true);marketError('');error('');$('marketStatus').textContent='دریافت و کنترل تاریخچه '+symbol+'…';let start=false;
 try{const d=await marketRequest('/api/market/history?symbol='+encodeURIComponent(symbol));const csv=['Date,Symbol,Open,High,Low,Close,Adj Close,Volume',...d.rows.map(r=>[r.date,d.symbol,r.open,r.high,r.low,r.close,r.adjClose,r.volume].join(','))].join('\n');const {rows:unused,...meta}=d;load(csv,d.source+' · '+d.symbol,false,meta);const box=$('instrument');box.replaceChildren();const name=document.createElement('b');name.textContent=d.name;const identity=document.createElement('div');identity.textContent=d.symbol+' · '+d.exchange+' · '+d.currency+' · '+d.instrumentType;const dates=document.createElement('small');dates.textContent=d.available+' جلسه · '+d.firstDate+' تا '+d.lastDate;box.append(name,identity,dates);box.hidden=false;$('marketStatus').textContent='تاریخچه دریافت شد؛ '+d.incomplete+' جلسه ناتمام و '+d.skipped+' ردیف ناقص کنار گذاشته شد.';if(!d.sufficient){marketError(d.warning+' ('+d.available+' از حداقل '+d.minimum+' ردیف)');}else start=true;}catch(e){marketError(e.name==='AbortError'?'دریافت لغو شد.':e.message);$('marketStatus').textContent='';}finally{marketController=null;marketBusy(false);}if(start)$('run').click();};
$('cancelMarket').onclick=()=>marketController?.abort();

if(window.DAYRIXA_OFFLINE){$('onlineSection').hidden=true;}
